import { Log } from "../util/log"
import { Filesystem } from "../util/filesystem"
import { Pakalon } from "./index"
import path from "path"
import fs from "fs/promises"

const log = Log.create({ service: "pakalon:normal-mode" })

export interface NormalModeArtifacts {
  planMd: string
  taskMd: string
  userStoriesMd: string
  contextManagementMd: string
  skillsMd: string
}

export namespace NormalMode {
  export async function ensureStructure(projectPath: string): Promise<void> {
    const normalDir = Pakalon.normalDir(projectPath)
    const agentsDir = path.join(normalDir, "agents")

    await fs.mkdir(normalDir, { recursive: true })
    await fs.mkdir(agentsDir, { recursive: true })

    log.info("Normal mode structure created", { projectPath })
  }

  export async function generateArtifacts(projectPath: string, userPrompt: string, responses: Record<string, string>): Promise<NormalModeArtifacts> {
    const normalDir = Pakalon.normalDir(projectPath)
    const agentsDir = path.join(normalDir, "agents")

    const artifacts: NormalModeArtifacts = {
      planMd: generatePlanMd(userPrompt, responses),
      taskMd: generateTaskMd(userPrompt, responses),
      userStoriesMd: generateUserStoriesMd(userPrompt, responses),
      contextManagementMd: generateContextManagementMd(userPrompt, responses),
      skillsMd: generateSkillsMd(userPrompt, responses),
    }

    await fs.writeFile(path.join(normalDir, "plan.md"), artifacts.planMd)
    await fs.writeFile(path.join(normalDir, "task.md"), artifacts.taskMd)
    await fs.writeFile(path.join(normalDir, "user-stories.md"), artifacts.userStoriesMd)
    await fs.writeFile(path.join(normalDir, "context-management.md"), artifacts.contextManagementMd)
    await fs.writeFile(path.join(agentsDir, "skills.md"), artifacts.skillsMd)

    log.info("Normal mode artifacts generated", { projectPath })
    return artifacts
  }

  export async function exists(projectPath: string): Promise<boolean> {
    const normalDir = Pakalon.normalDir(projectPath)
    try {
      await fs.access(normalDir)
      return true
    } catch {
      return false
    }
  }

  export async function getPlan(projectPath: string): Promise<string | null> {
    const planPath = path.join(Pakalon.normalDir(projectPath), "plan.md")
    try {
      return await fs.readFile(planPath, "utf-8")
    } catch {
      return null
    }
  }
}

function generatePlanMd(prompt: string, responses: Record<string, string>): string {
  return `# Project Plan

## User Request
${prompt}

## Technology Stack
- Frontend: ${responses.frontend || "To be determined"}
- Backend: ${responses.backend || "To be determined"}
- Database: ${responses.database || "To be determined"}

## Implementation Plan

### Step 1: Setup
- Initialize project structure
- Install dependencies
- Configure development environment

### Step 2: Core Development
- Implement main features
- Set up API endpoints
- Create database schema

### Step 3: Integration
- Connect frontend to backend
- Implement authentication
- Handle error states

### Step 4: Testing
- Unit tests
- Integration tests
- End-to-end tests

### Step 5: Deployment
- Configure production environment
- Deploy application
- Monitor and maintain

---
*Generated by Pakalon Normal Mode*
*Date: ${new Date().toISOString()}*
`
}

function generateTaskMd(prompt: string, responses: Record<string, string>): string {
  return `# Task List

## Setup Tasks
- [ ] Initialize project
- [ ] Install dependencies
- [ ] Configure environment

## Development Tasks
- [ ] Implement core features
- [ ] Create API endpoints
- [ ] Set up database

## Testing Tasks
- [ ] Write unit tests
- [ ] Write integration tests
- [ ] Perform manual testing

## Deployment Tasks
- [ ] Configure deployment
- [ ] Deploy to production
- [ ] Verify deployment

---
*Generated by Pakalon Normal Mode*
*Date: ${new Date().toISOString()}*
`
}

function generateUserStoriesMd(prompt: string, _responses: Record<string, string>): string {
  return `# User Stories

## US-001: Core Functionality
As a user, I want to ${prompt.toLowerCase().slice(0, 100)} so that I can accomplish my goals.

**Acceptance Criteria:**
- Feature works as expected
- Error handling is implemented
- Performance is acceptable

**Test Scenarios:**
- Happy path works
- Error cases handled
- Edge cases covered

---
*Generated by Pakalon Normal Mode*
*Date: ${new Date().toISOString()}*
`
}

function generateContextManagementMd(_prompt: string, _responses: Record<string, string>): string {
  return `# Context Management

## Token Budget
- Total Available: Based on model context window
- Buffer: 10% reserved
- Usable: 90% of total

## Allocation
- Planning: 20%
- Development: 60%
- Testing: 15%
- Buffer: 5%

## Optimization
- Read files in chunks
- Use search for specific content
- Summarize completed work

---
*Generated by Pakalon Normal Mode*
*Date: ${new Date().toISOString()}*
`
}

function generateSkillsMd(_prompt: string, responses: Record<string, string>): string {
  return `# Agent Skills

## Required Skills
- Frontend development (${responses.frontend || "React"})
- Backend development (${responses.backend || "Node.js"})
- Database management (${responses.database || "PostgreSQL"})
- Testing and QA
- Deployment and DevOps

## Recommended Skills
- UI/UX design
- API design
- Security best practices
- Performance optimization

---
*Generated by Pakalon Normal Mode*
*Date: ${new Date().toISOString()}*
`
}

export default NormalMode
