/**
 * System Prompt Builder — Dynamic system prompt generation.
 *
 * Generates the system prompt for the agent based on current context:
 * - Available tools and their descriptions
 * - Loaded skills with descriptions
 * - Current session state (mode, permissions)
 * - Project context (from .pakalon/ files)
 * - Agent configuration
 *
 * Provides callback hooks for extensions to modify the prompt,
 * and a builder pattern for composing prompts from sections.
 *
 * Usage:
 *   const builder = new SystemPromptBuilder();
 *   builder.addSection("Tools", toolDescriptions);
 *   builder.addSection("Skills", skillsPrompt);
 *   builder.setContext({ projectDir: "/path/to/project" });
 *   const prompt = builder.build();
 */

import * as fs from "fs";
import * as path from "path";
import logger from "@/utils/logger.js";
import { formatSkillsForSystemPrompt } from "@/ai/skill-validator.js";
import { getGitContext } from "@/ai/git-context.js";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export interface SystemPromptContext {
  /** Current project directory */
  projectDir?: string;
  /** Current permission mode */
  permissionMode?: string;
  /** Current model ID */
  model?: string;
  /** List of available tools */
  tools?: Array<{ name: string; description: string; dangerous?: boolean }>;
  /** Loaded skills */
  skills?: Array<{ name: string; description: string; disableModelInvocation?: boolean }>;
  /** Environment information */
  environment?: {
    platform: string;
    shell: string;
    cwd: string;
  };
  /** Custom instructions from .pakalon/CLAUDE.md or similar */
  customInstructions?: string;
  /** Git context (formatted string for inclusion) */
  gitContext?: string;
}

export interface PromptSection {
  /** Section title */
  title: string;
  /** Section content */
  content: string;
  /** Priority (lower = earlier in prompt) */
  priority: number;
  /** Whether this section is required */
  required?: boolean;
}

export type PromptTransformFn = (prompt: string, context: SystemPromptContext) => string;

// ─────────────────────────────────────────────────────────────────────────────
// Prompt Builder
// ─────────────────────────────────────────────────────────────────────────────

export class SystemPromptBuilder {
  private sections: PromptSection[] = [];
  private context: SystemPromptContext = {};
  private transforms: PromptTransformFn[] = [];
  private autoGenerated = false;

  constructor(autoGenerate = true) {
    this.autoGenerated = autoGenerate;
  }

  /**
   * Set the context for prompt generation.
   */
  setContext(context: Partial<SystemPromptContext>): this {
    this.context = { ...this.context, ...context };
    return this;
  }

  /**
   * Add a section to the prompt.
   */
  addSection(
    title: string,
    content: string,
    priority = 50,
    required = false,
  ): this {
    // Skip empty sections unless required
    if (!content.trim() && !required) return this;

    this.sections.push({ title, content, priority, required });
    return this;
  }

  /**
   * Add a transform function that runs after all sections are composed.
   */
  addTransform(fn: PromptTransformFn): this {
    this.transforms.push(fn);
    return this;
  }

  /**
   * Update a section's content if it exists, or add it if it doesn't.
   */
  upsertSection(title: string, content: string, priority = 50): this {
    const existing = this.sections.find((s) => s.title === title);
    if (existing) {
      existing.content = content;
    } else {
      this.sections.push({ title, content, priority, required: false });
    }
    return this;
  }

  /**
   * Auto-generate common sections from context.
   */
  autoGenerateSections(): this {
    if (!this.autoGenerated) return this;

    const ctx = this.context;

    // Identity section
    this.addSection(
      "Identity",
      "You are Pakalon, an AI-powered CLI coding assistant. You help users build, debug, and understand software projects.",
      0,
      true,
    );

    // Capabilities section
    const toolNames = ctx.tools?.map((t) => `- \`${t.name}\`: ${t.description}`).join("\n") ?? "";
    if (toolNames) {
      this.addSection(
        "Available Tools",
        `You have access to the following tools to help you accomplish tasks:\n\n${toolNames}`,
        10,
      );
    }

    // Skills section — uses formatSkillsForSystemPrompt from skill-validator
    if (ctx.skills && ctx.skills.length > 0) {
      const skillsText = formatSkillsForSystemPrompt(
        ctx.skills.map((s) => ({
          frontmatter: {
            name: s.name,
            description: s.description,
            disableModelInvocation: s.disableModelInvocation,
          },
        })),
        true,
      );
      if (skillsText.trim()) {
        this.addSection("Available Skills", skillsText, 20);
      }
    }

    // Environment section
    if (ctx.environment) {
      this.addSection(
        "Environment",
        [
          `Platform: ${ctx.environment.platform}`,
          `Shell: ${ctx.environment.shell}`,
          `Working Directory: ${ctx.environment.cwd}`,
        ].join("\n"),
        30,
      );
    }

    // Git status section
    if (ctx.gitContext) {
      this.addSection(
        "Git Status",
        ctx.gitContext,
        35,
      );
    }

    // Permission mode
    if (ctx.permissionMode) {
      this.addSection(
        "Permission Mode",
        `Current permission mode: ${ctx.permissionMode}. ${
          ctx.permissionMode === "yolo"
            ? "All tool executions are automatically approved."
            : ctx.permissionMode === "autonomous"
              ? "Allowed tools run without prompts; denied tools are blocked."
              : "You may need to ask for permission before executing certain tools."
        }`,
        40,
      );
    }

    // Custom instructions from project config
    if (ctx.customInstructions) {
      this.addSection("Custom Instructions", ctx.customInstructions, 60);
    }

    return this;
  }

  /**
   * Build the final system prompt.
   * Sorts sections by priority, joins them, applies transforms.
   */
  build(): string {
    if (this.autoGenerated) {
      this.autoGenerateSections();
    }

    // Sort sections by priority
    const sorted = [...this.sections].sort((a, b) => a.priority - b.priority);

    // Build the prompt
    const parts: string[] = [];
    for (const section of sorted) {
      if (!section.content.trim() && !section.required) continue;
      parts.push(`## ${section.title}`);
      parts.push("");
      parts.push(section.content.trim());
      parts.push("");
    }

    let prompt = parts.join("\n").trim();

    // Apply transforms in order
    for (const transform of this.transforms) {
      try {
        prompt = transform(prompt, this.context);
      } catch (err) {
        logger.warn("[SystemPrompt] Transform error", { error: String(err) });
      }
    }

    return prompt;
  }

  /**
   * Clear all sections and context.
   */
  clear(): this {
    this.sections = [];
    this.context = {};
    this.transforms = [];
    return this;
  }

  /**
   * Export the current builder state as JSON.
   */
  serialize(): string {
    return JSON.stringify({
      sections: this.sections,
      context: this.context,
    });
  }

  /**
   * Import a previously exported builder state.
   */
  static deserialize(json: string): SystemPromptBuilder {
    const data = JSON.parse(json);
    const builder = new SystemPromptBuilder(false);
    builder.sections = data.sections ?? [];
    builder.context = data.context ?? {};
    return builder;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Context Loader
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Load custom instructions from .pakalon/CLAUDE.md and related files.
 */
export function loadCustomInstructions(projectDir?: string): string {
  const dir = projectDir ?? process.cwd();
  const candidates = [
    path.join(dir, ".pakalon", "CLAUDE.md"),
    path.join(dir, ".pakalon", "instructions.md"),
    path.join(dir, ".pakalon", "plan.md"),
  ];

  const parts: string[] = [];

  for (const filePath of candidates) {
    try {
      if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, "utf-8").trim();
        if (content) {
          parts.push(`### From ${path.basename(filePath)}`);
          parts.push("");
          parts.push(content);
          parts.push("");
        }
      }
    } catch {
      // Skip unreadable files
    }
  }

  return parts.join("\n");
}

/**
 * Quick builder function for common use cases.
 */
export function buildSystemPrompt(context: SystemPromptContext): string {
  return new SystemPromptBuilder()
    .setContext(context)
    .build();
}
