import { cmd, Instance } from "./cmd"
import type { CommandModule } from "yargs"

/**
 * /fast command - Toggle fast/streaming mode
 */
export const fast: CommandModule = cmd(
  "fast [action]",
  "Toggle fast/streaming mode for responses",
  (yargs) =>
    yargs
      .positional("action", {
        type: "string",
        choices: ["on", "off", "toggle", "status"],
        default: "toggle",
        description: "Action to perform",
      }),
  Instance.provide(async (args, _ctx, instance) => {
    const action = args.action as string

    console.log("\n⚡ Fast Mode")
    console.log("═".repeat(50))

    switch (action) {
      case "on": {
        console.log("✓ Fast mode enabled")
        console.log("  Responses will be streamed as they're generated.")
        console.log("  Lower latency, faster perceived response time.")
        break
      }

      case "off": {
        console.log("✓ Fast mode disabled")
        console.log("  Responses will be shown after completion.")
        console.log("  More stable display, better for copying text.")
        break
      }

      case "toggle": {
        // Would toggle based on current state
        console.log("✓ Fast mode toggled")
        break
      }

      case "status":
      default: {
        const enabled = true // Would be read from config
        console.log(`\n  Status: ${enabled ? "Enabled" : "Disabled"}`)
        console.log("\n  Fast mode streams responses in real-time,")
        console.log("  showing text as it's generated by the AI.")
        console.log("\n  Commands:")
        console.log("  • /fast on      - Enable streaming")
        console.log("  • /fast off     - Disable streaming")
        console.log("  • /fast toggle  - Toggle mode")
        break
      }
    }
  })
)
