/**
 * Phase 6: documentation generator.
 *
 * Reads the project tree + Phase 1 docs and produces:
 *   - doc.md         (user-facing feature catalog)
 *   - README.md      (top-level)
 *   - API_DOCUMENTATION.md
 *   - CHANGELOG.md
 *   - ARCHITECTURE.md
 *   - CONTRIBUTING.md
 *   - phase-6.md     (work log)
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { logger } from "@oh-my-pi/pi-utils";

export interface Phase6Context {
	projectDir: string;
	phase6Dir: string;
	projectName: string;
	description: string;
}

function readIfExists(p: string): string {
	try {
		return fs.readFileSync(p, "utf-8");
	} catch {
		return "";
	}
}

function extractHeadings(md: string): string[] {
	const lines = md.split("\n");
	const headings: string[] = [];
	for (const line of lines) {
		const m = line.match(/^#+\s+(.+)/);
		if (m) headings.push(m[1] ?? "");
	}
	return headings;
}

export function generateDocMd(ctx: Phase6Context): string {
	const readme = readIfExists(path.join(ctx.projectDir, "README.md"));
	const api = readIfExists(path.join(ctx.projectDir, ".pakalon-agents", "ai-agents", "phase-1", "API_reference.md"));
	const plan = readIfExists(path.join(ctx.projectDir, ".pakalon-agents", "ai-agents", "phase-1", "plan.md"));
	const stories = readIfExists(
		path.join(ctx.projectDir, ".pakalon-agents", "ai-agents", "phase-1", "user-stories.md"),
	);
	const headings = extractHeadings(plan).slice(0, 10);
	return [
		`# ${ctx.projectName}`,
		``,
		ctx.description,
		``,
		`## Features`,
		``,
		headings.length > 0
			? headings.map(h => `- ${h}`).join("\n")
			: "_Features will be enumerated from the Phase 1 plan once it is finalized._",
		``,
		`## User stories`,
		``,
		stories || "_No user stories written yet._",
		``,
		`## API reference`,
		``,
		api || "_API reference is generated once the backend Phase 3 subagent writes the routes._",
		``,
		`## Getting started`,
		``,
		`1. Clone this repository.`,
		`2. Install dependencies (\`bun install\` or your package manager of choice).`,
		`3. Copy \`.env.example\` to \`.env\` and fill in the required keys.`,
		`4. Run the dev server (\`bun run dev\` or equivalent).`,
		``,
		`## What's in this repo`,
		``,
		readme ? readme.split("\n").slice(0, 30).join("\n") : "_Generated by Pakalon Phase 6._",
	].join("\n");
}

export function generateReadmeMd(ctx: Phase6Context, docPath: string): string {
	return [
		`# ${ctx.projectName}`,
		``,
		ctx.description,
		``,
		`Generated by [Pakalon](https://pakalon.dev) — the 6-phase AI SDLC CLI.`,
		``,
		`## Documentation`,
		``,
		`- [User-facing docs](${docPath})`,
		`- [API documentation](API_DOCUMENTATION.md)`,
		`- [Architecture](ARCHITECTURE.md)`,
		`- [Changelog](CHANGELOG.md)`,
		`- [Contributing](CONTRIBUTING.md)`,
	].join("\n");
}

export function generateApiDoc(ctx: Phase6Context): string {
	const api = readIfExists(path.join(ctx.projectDir, ".pakalon-agents", "ai-agents", "phase-1", "API_reference.md"));
	return [
		`# ${ctx.projectName} — API Documentation`,
		``,
		`Generated: ${new Date().toISOString()}`,
		``,
		api || "_No API reference was generated. Phase 3 subagent 2 must complete first._",
	].join("\n");
}

export function generateChangelogMd(ctx: Phase6Context): string {
	return [
		`# Changelog`,
		``,
		`## [Unreleased]`,
		``,
		`### Added`,
		``,
		`- Initial implementation generated by Pakalon.`,
		``,
		`_Project:_ ${ctx.projectName}`,
		`_Description:_ ${ctx.description}`,
	].join("\n");
}

export function generateArchitectureMd(ctx: Phase6Context): string {
	const db = readIfExists(path.join(ctx.projectDir, ".pakalon-agents", "ai-agents", "phase-1", "Database_schema.md"));
	return [
		`# ${ctx.projectName} — Architecture`,
		``,
		`## Tech stack`,
		``,
		`_See the Phase 1 \`plan.md\` for the full tech stack._`,
		``,
		`## Database schema`,
		``,
		db || "_No database schema was generated. The Phase 3 backend subagent must complete first._",
	].join("\n");
}

export function generateContributingMd(): string {
	return [
		`# Contributing`,
		``,
		`1. Fork this repository.`,
		`2. Create a feature branch.`,
		`3. Make your changes; add tests.`,
		`4. Run \`bun test\` and \`bun run check\`.`,
		`5. Open a pull request.`,
	].join("\n");
}

export function generatePhase6Summary(_ctx: Phase6Context, files: string[]): string {
	return [
		`# Phase 6: Documentation Summary`,
		``,
		`## Files generated`,
		``,
		...files.map(f => `- ${f}`),
		``,
		`## Notes`,
		``,
		`- The \`doc.md\` file at the project root is the user-facing feature catalog.`,
		`- \`README.md\` was updated to point to the docs.`,
		`- Phase 6 is optional in HIL mode; YOLO mode runs it automatically.`,
	].join("\n");
}

export function emitPhase6Files(ctx: Phase6Context): string[] {
	fs.mkdirSync(ctx.phase6Dir, { recursive: true });
	const docPath = "doc.md";
	const files = [
		{ relPath: docPath, content: generateDocMd(ctx) },
		{ relPath: "README.md", content: generateReadmeMd(ctx, docPath) },
		{ relPath: "API_DOCUMENTATION.md", content: generateApiDoc(ctx) },
		{ relPath: "CHANGELOG.md", content: generateChangelogMd(ctx) },
		{ relPath: "ARCHITECTURE.md", content: generateArchitectureMd(ctx) },
		{ relPath: "CONTRIBUTING.md", content: generateContributingMd() },
	];
	const written: string[] = [];
	for (const f of files) {
		fs.writeFileSync(path.join(ctx.projectDir, f.relPath), f.content, "utf-8");
		written.push(f.relPath);
	}
	const summary = generatePhase6Summary(ctx, written);
	fs.writeFileSync(path.join(ctx.phase6Dir, "phase-6.md"), summary, "utf-8");
	written.push("phase-6.md");
	logger.info("Phase 6 emitted", { count: written.length });
	return written;
}
