import fs from "fs";
import path from "path";

export type PipelinePhaseStatus = "complete" | "incomplete";

export interface PipelinePhaseState {
  phase: number;
  status: PipelinePhaseStatus;
  completedAt?: string;
  files: string[];
  missingRequiredFiles: string[];
}

export interface PipelineState {
  version: 1;
  projectDir: string;
  highestCompletedPhase: number;
  nextPhase: number | null;
  hasAgentsOutput: boolean;
  manifestPath: string;
  phases: PipelinePhaseState[];
  updatedAt?: string;
}

export interface PipelineStateManifest {
  version: 1;
  projectDir: string;
  phases: Record<string, {
    status: PipelinePhaseStatus;
    completedAt?: string;
    files?: string[];
  }>;
  updatedAt: string;
}

const PHASE_REQUIRED_FILES: Record<number, string[]> = {
  1: ["phase-1.md", "plan.md", "tasks.md", "context_management.md"],
  2: ["phase-2.md", "Wireframe_generated.svg", "Wireframe_generated.json", "Wireframe_generated.penpot"],
  3: ["execution_log.md", "subagent-5.md"],
  4: ["phase-4.md", "blackbox_testing.xml", "whitebox_testing.xml"],
  5: ["phase-5.md"],
  6: ["phase-6.md", "doc.md"],
};

const PLACEHOLDER_PATTERNS = [
  "_Generated by `/pakalon`",
  "## Status: PENDING",
  "_Log of all activities performed",
  "This phase generates wireframes based on the design.md from Phase 1.",
  "This placeholder file marks the expected phase-2 Penpot output.",
  "Sub-agent 1 (SAST) populates this during Phase-4 execution.",
  "Sub-agent 3 (Code Review) populates this during Phase-4 execution.",
];

function agentsRoot(projectDir: string): string {
  return path.join(projectDir, ".pakalon-agents");
}

function phaseDir(projectDir: string, phase: number): string {
  return path.join(agentsRoot(projectDir), "ai-agents", `phase-${phase}`);
}

function manifestPath(projectDir: string): string {
  return path.join(agentsRoot(projectDir), "pipeline-state.json");
}

function hasNonPlaceholderFile(filePath: string): boolean {
  if (!fs.existsSync(filePath)) return false;
  const stat = fs.statSync(filePath);
  if (!stat.isFile() || stat.size === 0) return false;

  const content = fs.readFileSync(filePath, "utf8").slice(0, 4000);
  return !PLACEHOLDER_PATTERNS.some((pattern) => content.includes(pattern));
}

function readManifest(projectDir: string): PipelineStateManifest | null {
  const filePath = manifestPath(projectDir);
  if (!fs.existsSync(filePath)) return null;

  try {
    const parsed = JSON.parse(fs.readFileSync(filePath, "utf8")) as PipelineStateManifest;
    return parsed.version === 1 && parsed.phases ? parsed : null;
  } catch {
    return null;
  }
}

function listAgentsOutput(projectDir: string): string[] {
  const root = agentsRoot(projectDir);
  if (!fs.existsSync(root)) return [];
  return fs.readdirSync(root).filter((entry) => entry !== "pipeline-state.json");
}

export function detectPipelineState(projectDir: string): PipelineState {
  const resolvedProjectDir = path.resolve(projectDir);
  const manifest = readManifest(resolvedProjectDir);
  const phases: PipelinePhaseState[] = [];

  for (let phase = 1; phase <= 6; phase++) {
    const required = PHASE_REQUIRED_FILES[phase] ?? [];
    const missingRequiredFiles = required.filter((file) => !hasNonPlaceholderFile(path.join(phaseDir(resolvedProjectDir, phase), file)));
    const manifestPhase = manifest?.phases?.[String(phase)];
    const manifestComplete = manifestPhase?.status === "complete";
    const status: PipelinePhaseStatus = manifestComplete || missingRequiredFiles.length === 0 ? "complete" : "incomplete";

    phases.push({
      phase,
      status,
      completedAt: manifestPhase?.completedAt,
      files: manifestPhase?.files ?? [],
      missingRequiredFiles: status === "complete" ? [] : missingRequiredFiles,
    });
  }

  const completed = phases.filter((phase) => phase.status === "complete").map((phase) => phase.phase);
  const highestCompletedPhase = completed.length ? Math.max(...completed) : 0;
  const nextIncomplete = phases.find((phase) => phase.status !== "complete")?.phase ?? null;

  return {
    version: 1,
    projectDir: resolvedProjectDir,
    highestCompletedPhase,
    nextPhase: nextIncomplete,
    hasAgentsOutput: listAgentsOutput(resolvedProjectDir).length > 0,
    manifestPath: manifestPath(resolvedProjectDir),
    phases,
    updatedAt: manifest?.updatedAt,
  };
}

export function markPipelinePhaseComplete(projectDir: string, phase: number, files: string[] = []): PipelineStateManifest {
  const resolvedProjectDir = path.resolve(projectDir);
  const filePath = manifestPath(resolvedProjectDir);
  const now = new Date().toISOString();
  const existing = readManifest(resolvedProjectDir);
  const manifest: PipelineStateManifest = existing ?? {
    version: 1,
    projectDir: resolvedProjectDir,
    phases: {},
    updatedAt: now,
  };

  manifest.projectDir = resolvedProjectDir;
  manifest.updatedAt = now;
  manifest.phases[String(phase)] = {
    status: "complete",
    completedAt: now,
    files: files.map((file) => path.resolve(file)),
  };

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  return manifest;
}

export function formatPipelineStateSummary(state: PipelineState): string {
  const phaseLine = state.phases
    .map((phase) => `${phase.phase}:${phase.status === "complete" ? "done" : "todo"}`)
    .join(" ");
  const next = state.nextPhase === null ? "all phases complete" : `next Phase ${state.nextPhase}`;

  return [
    `Pipeline state: ${phaseLine}`,
    `Highest completed phase: ${state.highestCompletedPhase || "none"}; ${next}.`,
  ].join("\n");
}

