import { Log } from "../util/log"
import { FileStructure } from "./file-structure"
import { AuditorAnalysis } from "./auditor-analysis"
import { Phase3Dev } from "./phase3-dev"
import type { PhaseContext } from "./types"
import type { PhaseNumber } from "../pakalon"

const log = Log.create({ service: "pipeline:auditor" })

export interface AuditorFinding {
  requirement: string
  status: "implemented" | "partial" | "missing"
  evidence: string
  recommendation: string
  files?: string[]
}

export interface AuditorReport {
  totalRequirements: number
  implemented: number
  partial: number
  missing: number
  coverage: number
  findings: AuditorFinding[]
  iterations: number
  passed: boolean
}

export namespace Auditor {
  const MAX_ITERATIONS = 10

  export async function scan(projectPath: string, phase: PhaseNumber): Promise<AuditorReport> {
    log.info("running auditor scan", { projectPath, phase })

    const phase1Content = await FileStructure.readArtifact(projectPath, 1, "plan.md")
    const tasksContent = await FileStructure.readArtifact(projectPath, 1, "tasks.md")
    const userStoriesContent = await FileStructure.readArtifact(projectPath, 1, "user-stories.md")

    const requirements = extractRequirements(phase1Content, tasksContent, userStoriesContent)
    const findings = await evaluateRequirements(projectPath, requirements)

    const implemented = findings.filter((f) => f.status === "implemented").length
    const partial = findings.filter((f) => f.status === "partial").length
    const missing = findings.filter((f) => f.status === "missing").length
    const coverage = requirements.length > 0 ? Math.round((implemented / requirements.length) * 100) : 0

    // Save auditor report
    const report = {
      totalRequirements: requirements.length,
      implemented,
      partial,
      missing,
      coverage,
      findings,
      iterations: 1,
      passed: coverage >= 80,
    }

    const reportContent = formatReport(report)
    await FileStructure.writeArtifact(projectPath, phase, "auditor.md", reportContent)

    return report
  }

  export async function loop(projectPath: string, mode: "hil" | "yolo"): Promise<AuditorReport> {
    log.info("starting auditor loop", { mode })

    let report = await scan(projectPath, 3)
    let iteration = 1

    while (!report.passed && iteration < MAX_ITERATIONS) {
      log.info("auditor iteration", { iteration, coverage: report.coverage })

      // In YOLO mode, automatically trigger fixes
      if (mode === "yolo") {
        await triggerFixes(projectPath, report)
      } else {
        // In HIL mode, ask user for action
        log.info("auditor found issues", { missing: report.missing, partial: report.partial })
        break
      }

      iteration++
      report = await scan(projectPath, 3)
      report.iterations = iteration
    }

    return report
  }

  export function formatReport(report: AuditorReport): string {
    const lines = [
      "# Auditor Report",
      "",
      `## Coverage: ${report.coverage}%`,
      "",
      `**Total Requirements:** ${report.totalRequirements}`,
      `**Implemented:** ${report.implemented}`,
      `**Partial:** ${report.partial}`,
      `**Missing:** ${report.missing}`,
      `**Iterations:** ${report.iterations}`,
      `**Status:** ${report.passed ? "✅ PASSED" : "❌ NEEDS WORK"}`,
      "",
      "## Findings",
      "",
    ]

    for (const finding of report.findings) {
      const icon = finding.status === "implemented" ? "✅" : finding.status === "partial" ? "⚠️" : "❌"
      lines.push(`### ${icon} ${finding.requirement}`)
      lines.push(`**Status:** ${finding.status}`)
      lines.push(`**Evidence:** ${finding.evidence}`)
      if (finding.files && finding.files.length > 0) {
        lines.push(`**Files:** ${finding.files.join(", ")}`)
      }
      lines.push(`**Recommendation:** ${finding.recommendation}`)
      lines.push("")
    }

    lines.push("---")
    lines.push("*Generated by Pakalon Auditor Agent*")

    return lines.join("\n")
  }

  function extractRequirements(
    planContent?: string,
    tasksContent?: string,
    userStoriesContent?: string,
  ): string[] {
    const reqs: string[] = []

    if (planContent) {
      const lines = planContent.split("\n")
      for (const line of lines) {
        if (line.startsWith("- ") || line.startsWith("* ")) {
          reqs.push(line.slice(2).trim())
        }
        if (line.match(/^#+\s+/)) {
          reqs.push(line.replace(/^#+\s+/, "").trim())
        }
      }
    }

    if (tasksContent) {
      const taskMatches = tasksContent.match(/- \[[ x]\] .+/g)
      if (taskMatches) {
        for (const match of taskMatches) {
          reqs.push(match.replace(/- \[[ x]\] /, "").trim())
        }
      }
    }

    if (userStoriesContent) {
      const storyMatches = userStoriesContent.match(/### US-\d+:.+/g)
      if (storyMatches) {
        for (const match of storyMatches) {
          reqs.push(match.replace("### ", "").trim())
        }
      }
    }

    return [...new Set(reqs)].filter((r) => r.length > 3)
  }

  async function evaluateRequirements(
    projectPath: string,
    requirements: string[],
  ): Promise<AuditorFinding[]> {
    const analysis = await AuditorAnalysis.analyzeCodebase(projectPath).catch(() => undefined)
    const findings: AuditorFinding[] = []

    for (const req of requirements) {
      const finding = await evaluateSingleRequirement(projectPath, req, analysis)
      findings.push(finding)
    }

    return findings
  }

  async function evaluateSingleRequirement(
    projectPath: string,
    requirement: string,
    analysis?: Awaited<ReturnType<typeof AuditorAnalysis.analyzeCodebase>>,
  ): Promise<AuditorFinding> {
    const keywords = requirement.toLowerCase().split(/\s+/)
    const reqLower = requirement.toLowerCase()
    const deep = getDeepFinding(requirement, reqLower, analysis)
    if (deep) return deep

    // Enhanced pattern detection with context awareness
    const patterns = analysis ? convertAnalysis(analysis) : await detectAllPatterns(projectPath)

    // Auth-related requirements
    if (keywords.some((k) => ["auth", "login", "register", "authentication", "jwt", "oauth"].includes(k))) {
      if (patterns.auth.found) {
        const score = calculateAuthCompleteness(patterns.auth)
        return {
          requirement,
          status: score >= 80 ? "implemented" : score >= 40 ? "partial" : "missing",
          evidence: `Auth implementation: ${patterns.auth.details.join("; ")}`,
          recommendation: score >= 80 ? "None needed" : getAuthRecommendations(patterns.auth),
          files: patterns.auth.files,
        }
      }
      return {
        requirement,
        status: "missing",
        evidence: "No authentication patterns found",
        recommendation: "Implement authentication with JWT/session management, login/register endpoints, and auth middleware",
      }
    }

    // Database requirements
    if (keywords.some((k) => ["database", "db", "schema", "data", "sql", "orm"].includes(k))) {
      if (patterns.database.found) {
        const score = calculateDbCompleteness(patterns.database)
        return {
          requirement,
          status: score >= 70 ? "implemented" : score >= 35 ? "partial" : "missing",
          evidence: `Database setup: ${patterns.database.details.join("; ")}`,
          recommendation: score >= 70 ? "None needed" : getDbRecommendations(patterns.database),
          files: patterns.database.files,
        }
      }
      return {
        requirement,
        status: "missing",
        evidence: "No database patterns found",
        recommendation: "Set up database with schema, migrations, and ORM configuration",
      }
    }

    // API requirements
    if (keywords.some((k) => ["api", "endpoint", "route", "rest", "graphql", "controller"].includes(k))) {
      if (patterns.api.found) {
        const score = calculateApiCompleteness(patterns.api)
        return {
          requirement,
          status: score >= 60 ? "implemented" : score >= 30 ? "partial" : "missing",
          evidence: `API implementation: ${patterns.api.details.join("; ")}`,
          recommendation: score >= 60 ? "None needed" : getApiRecommendations(patterns.api),
          files: patterns.api.files,
        }
      }
      return {
        requirement,
        status: "missing",
        evidence: "No API patterns found",
        recommendation: "Implement API routes with proper validation and error handling",
      }
    }

    // Frontend/UI requirements
    if (keywords.some((k) => ["frontend", "ui", "component", "page", "interface", "view", "react", "vue"].includes(k))) {
      if (patterns.frontend.found) {
        const score = calculateFrontendCompleteness(patterns.frontend)
        return {
          requirement,
          status: score >= 50 ? "implemented" : score >= 25 ? "partial" : "missing",
          evidence: `Frontend implementation: ${patterns.frontend.details.join("; ")}`,
          recommendation: score >= 50 ? "None needed" : getFrontendRecommendations(patterns.frontend),
          files: patterns.frontend.files,
        }
      }
      return {
        requirement,
        status: "missing",
        evidence: "No frontend components found",
        recommendation: "Implement UI components, pages, and styling",
      }
    }

    // Testing requirements
    if (keywords.some((k) => ["test", "testing", "spec", "coverage", "unit", "integration"].includes(k))) {
      if (patterns.testing.found) {
        const score = calculateTestCompleteness(patterns.testing)
        return {
          requirement,
          status: score >= 60 ? "implemented" : score >= 30 ? "partial" : "missing",
          evidence: `Testing setup: ${patterns.testing.details.join("; ")}`,
          recommendation: score >= 60 ? "None needed" : "Add more test coverage",
          files: patterns.testing.files,
        }
      }
      return {
        requirement,
        status: "missing",
        evidence: "No test files found",
        recommendation: "Add unit tests, integration tests, and test configuration",
      }
    }

    // CI/CD requirements
    if (keywords.some((k) => ["ci", "cd", "pipeline", "github", "deploy", "workflow"].includes(k))) {
      if (patterns.cicd.found) {
        return {
          requirement,
          status: "implemented",
          evidence: `CI/CD configuration: ${patterns.cicd.details.join("; ")}`,
          recommendation: "None needed",
          files: patterns.cicd.files,
        }
      }
      return {
        requirement,
        status: "missing",
        evidence: "No CI/CD configuration found",
        recommendation: "Set up GitHub Actions workflows for testing, building, and deployment",
      }
    }

    // Docker/Container requirements
    if (keywords.some((k) => ["docker", "container", "compose", "deployment"].includes(k))) {
      if (patterns.docker.found) {
        return {
          requirement,
          status: "implemented",
          evidence: `Docker setup: ${patterns.docker.details.join("; ")}`,
          recommendation: "None needed",
          files: patterns.docker.files,
        }
      }
      return {
        requirement,
        status: "missing",
        evidence: "No Docker configuration found",
        recommendation: "Add Dockerfile and docker-compose.yml for containerization",
      }
    }

    // Security requirements
    if (keywords.some((k) => ["security", "vulnerability", "scan", "audit", "xss", "csrf", "injection"].includes(k))) {
      if (patterns.security.found) {
        return {
          requirement,
          status: "implemented",
          evidence: `Security measures: ${patterns.security.details.join("; ")}`,
          recommendation: "None needed",
          files: patterns.security.files,
        }
      }
      return {
        requirement,
        status: "missing",
        evidence: "No security measures found",
        recommendation: "Add security scanning, input validation, and OWASP protections",
      }
    }

    // Documentation requirements
    if (keywords.some((k) => ["documentation", "docs", "readme", "guide", "api-docs"].includes(k))) {
      if (patterns.docs.found) {
        return {
          requirement,
          status: "implemented",
          evidence: `Documentation: ${patterns.docs.details.join("; ")}`,
          recommendation: "None needed",
          files: patterns.docs.files,
        }
      }
      return {
        requirement,
        status: "partial",
        evidence: "Limited documentation found",
        recommendation: "Add README, API documentation, and user guides",
      }
    }

    // Generic requirement - check for any relevant implementation
    const relevantPatterns = findRelevantPatterns(reqLower, patterns)
    if (relevantPatterns.length > 0) {
      return {
        requirement,
        status: "partial",
        evidence: `Found related implementation: ${relevantPatterns.join("; ")}`,
        recommendation: "Verify this implementation fully covers the requirement",
      }
    }

    // Check if there's any code at all
    if (patterns.general.codeFiles > 0) {
      return {
        requirement,
        status: "partial",
        evidence: `Codebase exists (${patterns.general.codeFiles} files) but requirement coverage unclear`,
        recommendation: "Review implementation to verify requirement is addressed",
      }
    }

    return {
      requirement,
      status: "missing",
      evidence: "No implementation found for this requirement",
      recommendation: "Implement the required functionality",
    }
  }

  // Enhanced pattern detection
  interface PatternSet {
    found: boolean
    details: string[]
    files: string[]
    metadata: Record<string, any>
  }

  interface AllPatterns {
    auth: PatternSet
    database: PatternSet
    api: PatternSet
    frontend: PatternSet
    testing: PatternSet
    cicd: PatternSet
    docker: PatternSet
    security: PatternSet
    docs: PatternSet
    general: { codeFiles: number; totalLines: number }
  }

  async function detectAllPatterns(projectPath: string): Promise<AllPatterns> {
    const patterns: AllPatterns = {
      auth: { found: false, details: [], files: [], metadata: {} },
      database: { found: false, details: [], files: [], metadata: {} },
      api: { found: false, details: [], files: [], metadata: {} },
      frontend: { found: false, details: [], files: [], metadata: {} },
      testing: { found: false, details: [], files: [], metadata: {} },
      cicd: { found: false, details: [], files: [], metadata: {} },
      docker: { found: false, details: [], files: [], metadata: {} },
      security: { found: false, details: [], files: [], metadata: {} },
      docs: { found: false, details: [], files: [], metadata: {} },
      general: { codeFiles: 0, totalLines: 0 },
    }

    try {
      const fs = await import("fs/promises")
      const path = await import("path")

      async function scanDir(dir: string, depth = 0): Promise<void> {
        if (depth > 5) return // Prevent infinite recursion

        try {
          const entries = await fs.readdir(dir, { withFileTypes: true })

          for (const entry of entries) {
            const fullPath = path.join(dir, entry.name)

            // Skip hidden directories and node_modules
            if (entry.name.startsWith(".") || entry.name === "node_modules" || entry.name === "dist" || entry.name === "build") {
              continue
            }

            if (entry.isDirectory()) {
              await scanDir(fullPath, depth + 1)
            } else if (entry.isFile()) {
              const ext = path.extname(entry.name).toLowerCase()
              const isCodeFile = [".ts", ".tsx", ".js", ".jsx", ".py", ".go", ".rs", ".java"].includes(ext)
              const isConfigFile = [".json", ".yml", ".yaml", ".toml", ".env"].includes(ext)
              const isDocFile = [".md", ".txt", ".rst"].includes(ext)

              if (!isCodeFile && !isConfigFile && !isDocFile) continue

              const content = await fs.readFile(fullPath, "utf-8").catch(() => "")
              if (!content) continue

              const fileName = path.relative(projectPath, fullPath)
              const lines = content.split("\n").length

              if (isCodeFile) {
                patterns.general.codeFiles++
                patterns.general.totalLines += lines
              }

              // Auth detection
              if (content.match(/jwt|jsonwebtoken|auth|login|register|session|passport|oauth/i)) {
                patterns.auth.found = true
                patterns.auth.files.push(fileName)
                if (content.includes("jwt") || content.includes("jsonwebtoken")) patterns.auth.details.push("JWT")
                if (content.includes("passport")) patterns.auth.details.push("Passport.js")
                if (content.includes("oauth")) patterns.auth.details.push("OAuth")
                if (content.match(/login|register|signup/i)) patterns.auth.details.push("Auth endpoints")
                if (content.match(/middleware.*auth|auth.*middleware/i)) patterns.auth.details.push("Auth middleware")
              }

              // Database detection
              if (content.match(/prisma|drizzle|sequelize|typeorm|mongoose|knex|sql|schema.*model|migration/i)) {
                patterns.database.found = true
                patterns.database.files.push(fileName)
                if (content.includes("prisma")) patterns.database.details.push("Prisma")
                if (content.includes("drizzle")) patterns.database.details.push("Drizzle")
                if (content.includes("sequelize")) patterns.database.details.push("Sequelize")
                if (content.includes("mongoose")) patterns.database.details.push("Mongoose")
                if (content.match(/CREATE TABLE|ALTER TABLE/i)) patterns.database.details.push("SQL schema")
                if (content.match(/migration/i)) patterns.database.details.push("Migrations")
              }

              // API detection
              if (content.match(/router|route|endpoint|app\.(get|post|put|delete|patch)|fastify|hono|express/i)) {
                patterns.api.found = true
                patterns.api.files.push(fileName)
                if (content.match(/app\.(get|post|put|delete)/i)) patterns.api.details.push("REST endpoints")
                if (content.includes("graphql")) patterns.api.details.push("GraphQL")
                if (content.match(/router|Router/)) patterns.api.details.push("Router")
                if (content.match(/middleware/i)) patterns.api.details.push("Middleware")
              }

              // Frontend detection
              if (content.match(/react|vue|svelte|angular|useState|component|jsx|tsx/i)) {
                patterns.frontend.found = true
                patterns.frontend.files.push(fileName)
                if (content.match(/useState|useEffect|React/i)) patterns.frontend.details.push("React")
                if (content.match(/Vue|createApp/i)) patterns.frontend.details.push("Vue")
                if (content.match(/Svelte/i)) patterns.frontend.details.push("Svelte")
                if (content.match(/className|style|css|tailwind/i)) patterns.frontend.details.push("Styling")
              }

              // Testing detection
              if (content.match(/describe|it\(|test\(|expect|jest|vitest|mocha|playwright|cypress/i)) {
                patterns.testing.found = true
                patterns.testing.files.push(fileName)
                if (content.match(/jest/i)) patterns.testing.details.push("Jest")
                if (content.match(/vitest/i)) patterns.testing.details.push("Vitest")
                if (content.match(/playwright/i)) patterns.testing.details.push("Playwright")
                if (content.match(/cypress/i)) patterns.testing.details.push("Cypress")
              }

              // CI/CD detection
              if (fileName.match(/\.github\/workflows|\.gitlab-ci|Jenkinsfile|\.circleci/i) || 
                  content.match(/uses:.*actions|workflow_dispatch|jobs:/i)) {
                patterns.cicd.found = true
                patterns.cicd.files.push(fileName)
                patterns.cicd.details.push("GitHub Actions")
              }

              // Docker detection
              if (fileName.match(/Dockerfile|docker-compose/i) || content.match(/FROM\s+\w+|docker/i)) {
                patterns.docker.found = true
                patterns.docker.files.push(fileName)
                if (fileName.includes("Dockerfile")) patterns.docker.details.push("Dockerfile")
                if (fileName.includes("docker-compose")) patterns.docker.details.push("Docker Compose")
              }

              // Security detection
              if (content.match(/helmet|cors|csrf|xss|sanitiz|validat|rate.?limit/i)) {
                patterns.security.found = true
                patterns.security.files.push(fileName)
                if (content.match(/helmet/i)) patterns.security.details.push("Helmet")
                if (content.match(/cors/i)) patterns.security.details.push("CORS")
                if (content.match(/csrf/i)) patterns.security.details.push("CSRF protection")
                if (content.match(/validat/i)) patterns.security.details.push("Input validation")
              }

              // Documentation detection
              if (isDocFile || fileName.match(/README|CHANGELOG|docs\//i)) {
                patterns.docs.found = true
                patterns.docs.files.push(fileName)
                if (fileName.match(/README/i)) patterns.docs.details.push("README")
                if (fileName.match(/CHANGELOG/i)) patterns.docs.details.push("Changelog")
                if (fileName.match(/docs\//i)) patterns.docs.details.push("Documentation folder")
              }
            }
          }
        } catch {
          // Directory doesn't exist or can't be read
        }
      }

      await scanDir(projectPath)

      // Deduplicate details
      for (const key of Object.keys(patterns)) {
        if (key !== "general" && patterns[key as keyof AllPatterns]) {
          const p = patterns[key as keyof AllPatterns] as PatternSet
          p.details = [...new Set(p.details)]
          p.files = [...new Set(p.files)]
        }
      }
    } catch {
      // Error scanning
    }

    return patterns
  }

  function calculateAuthCompleteness(auth: PatternSet): number {
    let score = 0
    if (auth.details.includes("JWT")) score += 25
    if (auth.details.includes("Passport.js")) score += 25
    if (auth.details.includes("OAuth")) score += 20
    if (auth.details.includes("Auth endpoints")) score += 20
    if (auth.details.includes("Auth middleware")) score += 15
    return Math.min(100, score)
  }

  function getAuthRecommendations(auth: PatternSet): string {
    const missing = []
    if (!auth.details.includes("JWT") && !auth.details.includes("Passport.js")) missing.push("token management")
    if (!auth.details.includes("Auth endpoints")) missing.push("login/register endpoints")
    if (!auth.details.includes("Auth middleware")) missing.push("auth middleware")
    return `Add: ${missing.join(", ")}`
  }

  function calculateDbCompleteness(db: PatternSet): number {
    let score = 0
    if (db.details.some(d => ["Prisma", "Drizzle", "Sequelize", "Mongoose"].includes(d))) score += 30
    if (db.details.includes("SQL schema")) score += 25
    if (db.details.includes("Migrations")) score += 25
    if (db.files.length > 2) score += 20
    return Math.min(100, score)
  }

  function getDbRecommendations(db: PatternSet): string {
    const missing = []
    if (!db.details.some(d => ["Prisma", "Drizzle", "Sequelize", "Mongoose"].includes(d))) missing.push("ORM setup")
    if (!db.details.includes("SQL schema") && !db.details.includes("Migrations")) missing.push("schema and migrations")
    return `Add: ${missing.join(", ")}`
  }

  function calculateApiCompleteness(api: PatternSet): number {
    let score = 0
    if (api.details.includes("REST endpoints")) score += 30
    if (api.details.includes("Router")) score += 25
    if (api.details.includes("Middleware")) score += 20
    if (api.details.includes("GraphQL")) score += 25
    if (api.files.length > 3) score += 15
    return Math.min(100, score)
  }

  function getApiRecommendations(api: PatternSet): string {
    const missing = []
    if (!api.details.includes("REST endpoints") && !api.details.includes("GraphQL")) missing.push("API endpoints")
    if (!api.details.includes("Middleware")) missing.push("middleware (validation, error handling)")
    return `Add: ${missing.join(", ")}`
  }

  function calculateFrontendCompleteness(frontend: PatternSet): number {
    let score = 0
    if (frontend.details.includes("React") || frontend.details.includes("Vue") || frontend.details.includes("Svelte")) score += 35
    if (frontend.details.includes("Styling")) score += 25
    if (frontend.files.length > 5) score += 20
    if (frontend.files.length > 10) score += 20
    return Math.min(100, score)
  }

  function getFrontendRecommendations(frontend: PatternSet): string {
    const missing = []
    if (!frontend.details.some(d => ["React", "Vue", "Svelte"].includes(d))) missing.push("UI framework")
    if (!frontend.details.includes("Styling")) missing.push("styling/CSS")
    if (frontend.files.length < 5) missing.push("more components")
    return `Add: ${missing.join(", ")}`
  }

  function calculateTestCompleteness(testing: PatternSet): number {
    let score = 0
    if (testing.details.includes("Jest") || testing.details.includes("Vitest")) score += 35
    if (testing.details.includes("Playwright") || testing.details.includes("Cypress")) score += 30
    if (testing.files.length > 3) score += 20
    if (testing.files.length > 10) score += 15
    return Math.min(100, score)
  }

  function findRelevantPatterns(requirement: string, patterns: AllPatterns): string[] {
    const relevant: string[] = []
    const keywords = requirement.split(/\s+/).filter(w => w.length > 3)

    for (const [key, value] of Object.entries(patterns)) {
      if (key === "general") continue
      const p = value as PatternSet
      if (p.found) {
        for (const keyword of keywords) {
          if (p.details.some(d => d.toLowerCase().includes(keyword)) ||
              p.files.some(f => f.toLowerCase().includes(keyword))) {
            relevant.push(`${key}: ${p.details.join(", ")}`)
            break
          }
        }
      }
    }

    return relevant
  }

  async function getImplementationDetails(
    projectPath: string,
    type: string,
  ): Promise<{ patterns: string[]; files: string[]; completeness: number }> {
    const details: { patterns: string[]; files: string[]; completeness: number } = {
      patterns: [],
      files: [],
      completeness: 0,
    }

    try {
      const fs = await import("fs/promises")
      const path = await import("path")

      async function scanForDetails(dir: string): Promise<void> {
        try {
          const entries = await fs.readdir(dir, { withFileTypes: true })

          for (const entry of entries) {
            const fullPath = path.join(dir, entry.name)

            if (entry.isDirectory() && !entry.name.startsWith(".") && entry.name !== "node_modules") {
              await scanForDetails(fullPath)
            } else if (entry.isFile() && (entry.name.endsWith(".ts") || entry.name.endsWith(".js") || entry.name.endsWith(".tsx") || entry.name.endsWith(".jsx"))) {
              const content = await fs.readFile(fullPath, "utf-8").catch(() => "")
              const fileName = path.relative(projectPath, fullPath)

              // Check for patterns based on type
              switch (type) {
                case "auth":
                  if (content.includes("jwt") || content.includes("token") || content.includes("session")) {
                    details.patterns.push("JWT/session handling")
                    details.files.push(fileName)
                    details.completeness += 20
                  }
                  if (content.includes("login") || content.includes("register")) {
                    details.patterns.push("Auth endpoints")
                    details.files.push(fileName)
                    details.completeness += 20
                  }
                  if (content.includes("middleware") && content.includes("auth")) {
                    details.patterns.push("Auth middleware")
                    details.files.push(fileName)
                    details.completeness += 30
                  }
                  break

                case "database":
                  if (content.includes("schema") || content.includes("model")) {
                    details.patterns.push("Database schema")
                    details.files.push(fileName)
                    details.completeness += 25
                  }
                  if (content.includes("migration")) {
                    details.patterns.push("Migrations")
                    details.files.push(fileName)
                    details.completeness += 25
                  }
                  if (content.includes("prisma") || content.includes("drizzle") || content.includes("sequelize")) {
                    details.patterns.push("ORM")
                    details.files.push(fileName)
                    details.completeness += 25
                  }
                  break

                case "api":
                  if (content.includes("router") || content.includes("route")) {
                    details.patterns.push("API routes")
                    details.files.push(fileName)
                    details.completeness += 20
                  }
                  if (content.includes("GET") || content.includes("POST") || content.includes("PUT") || content.includes("DELETE")) {
                    details.patterns.push("REST endpoints")
                    details.files.push(fileName)
                    details.completeness += 20
                  }
                  if (content.includes("validate") || content.includes("schema")) {
                    details.patterns.push("Validation")
                    details.files.push(fileName)
                    details.completeness += 15
                  }
                  break

                case "frontend":
                  if (content.includes("useState") || content.includes("reactive") || content.includes("computed")) {
                    details.patterns.push("State management")
                    details.files.push(fileName)
                    details.completeness += 15
                  }
                  if (content.includes("component") || content.includes("Component")) {
                    details.patterns.push("Components")
                    details.files.push(fileName)
                    details.completeness += 15
                  }
                  if (content.includes("style") || content.includes("className") || content.includes("css")) {
                    details.patterns.push("Styling")
                    details.files.push(fileName)
                    details.completeness += 10
                  }
                  break
              }
            }
          }
        } catch {
          // Directory doesn't exist or can't be read
        }
      }

      await scanForDetails(projectPath)

      // Normalize completeness to 0-100
      details.completeness = Math.min(100, details.completeness)

      // Remove duplicates
      details.patterns = [...new Set(details.patterns)]
      details.files = [...new Set(details.files)]
    } catch {
      // Error scanning
    }

    return details
  }

  async function checkForPattern(projectPath: string, patterns: string[]): Promise<boolean> {
    try {
      const fs = await import("fs/promises")
      const path = await import("path")

      async function scanDir(dir: string): Promise<boolean> {
        try {
          const entries = await fs.readdir(dir, { withFileTypes: true })

          for (const entry of entries) {
            const fullPath = path.join(dir, entry.name)

            if (entry.isDirectory() && !entry.name.startsWith(".") && entry.name !== "node_modules") {
              const found = await scanDir(fullPath)
              if (found) return true
            } else if (entry.isFile()) {
              const content = await fs.readFile(fullPath, "utf-8").catch(() => "")
              for (const pattern of patterns) {
                if (content.toLowerCase().includes(pattern)) {
                  return true
                }
              }
            }
          }
        } catch {
          // Directory doesn't exist or can't be read
        }
        return false
      }

      return await scanDir(projectPath)
    } catch {
      return false
    }
  }

  async function triggerFixes(projectPath: string, report: AuditorReport): Promise<void> {
    log.info("triggering fixes for missing requirements", {
      missing: report.missing,
      partial: report.partial,
    })

    // Group findings by status and priority
    const missingFindings = report.findings.filter((f) => f.status === "missing")
    const partialFindings = report.findings.filter((f) => f.status === "partial")

    // Create comprehensive fix tasks document
    let fixTasksContent = `# Auditor Fix Tasks

Generated: ${new Date().toISOString()}
Coverage: ${report.coverage}%

## Summary
- Missing: ${missingFindings.length} requirements
- Partial: ${partialFindings.length} requirements
- Total to fix: ${missingFindings.length + partialFindings.length}

## Priority Order
Fix missing requirements first, then enhance partial implementations.

---

`

    // Add missing requirements (high priority)
    if (missingFindings.length > 0) {
      fixTasksContent += `## Missing Requirements (High Priority)\n\n`
      for (let i = 0; i < missingFindings.length; i++) {
        const finding = missingFindings[i]
        fixTasksContent += generateFixTask(finding, "missing", i + 1)
        fixTasksContent += "\n"
      }
    }

    // Add partial requirements (medium priority)
    if (partialFindings.length > 0) {
      fixTasksContent += `## Partial Requirements (Medium Priority)\n\n`
      for (let i = 0; i < partialFindings.length; i++) {
        const finding = partialFindings[i]
        fixTasksContent += generateFixTask(finding, "partial", missingFindings.length + i + 1)
        fixTasksContent += "\n"
      }
    }

    // Add implementation instructions
    fixTasksContent += `
## Implementation Instructions

### For Subagents
1. Read the requirement carefully
2. Check existing codebase for similar patterns
3. Implement following project conventions
4. Add tests if applicable
5. Update documentation

### For YOLO Mode
The orchestrator will automatically spawn subagents to address each task.
Each subagent will:
- Focus on one requirement at a time
- Follow existing code patterns
- Create necessary files and tests
- Mark tasks as complete when done

### Verification
After all fixes:
1. Re-run auditor scan
2. Verify coverage increased
3. Check for any regressions

---
*Generated by Pakalon Auditor - Iteration will continue until 80%+ coverage*
`

    // Write fix tasks to file
    await FileStructure.writeArtifact(projectPath, 3, "fix-tasks.md", fixTasksContent)

    // Also create individual task files for subagent consumption
    const allFindings = [...missingFindings, ...partialFindings]
    for (let i = 0; i < allFindings.length; i++) {
      const finding = allFindings[i]
      const taskFileName = `fix-task-${i + 1}.md`
      const taskContent = generateIndividualTask(finding, i + 1)
      await FileStructure.writeArtifact(projectPath, 3, taskFileName, taskContent)
    }

    log.info("fix tasks generated", {
      missing: missingFindings.length,
      partial: partialFindings.length,
      totalFiles: allFindings.length + 1, // +1 for main fix-tasks.md
    })

    const ctx: PhaseContext = {
      phase: 3,
      projectPath,
      mode: "yolo",
      artifacts: ["fix-tasks.md", ...allFindings.map((_, i) => `fix-task-${i + 1}.md`)],
      memory: {
        auditor: report,
        fixTasks: {
          missing: missingFindings.length,
          partial: partialFindings.length,
          total: allFindings.length,
        },
      },
      tokenBudget: {
        total: 50_000,
        remaining: 50_000,
      },
    }

    const result = await Phase3Dev.execute(ctx)
    if (result.success) {
      log.info("fix execution completed", {
        artifacts: result.artifacts.length,
        tokensUsed: result.tokensUsed,
      })
      return
    }

    log.error("fix execution failed", {
      error: result.error,
      artifacts: result.artifacts.length,
    })
  }

  function getDeepFinding(
    requirement: string,
    req: string,
    analysis?: Awaited<ReturnType<typeof AuditorAnalysis.analyzeCodebase>>,
  ): AuditorFinding | undefined {
    if (!analysis) return
    const types = deepTypes(req)
    if (types.length === 0) return

    const rows = types
      .map((type) => analysis.patterns.find((p) => p.type === type))
      .filter((p): p is NonNullable<typeof p> => Boolean(p))
    if (rows.length === 0) return

    const best = rows.sort((a, b) => b.completeness - a.completeness)[0]
    const status = best.completeness >= 75 ? "implemented" : best.completeness >= 35 ? "partial" : "missing"
    const evidence = `${best.type}: ${best.details.join("; ")} (confidence ${best.confidence}%, completeness ${best.completeness}%)`
    const recommendation =
      status === "implemented"
        ? "None needed"
        : `Improve ${best.type} coverage and align implementation to requirement details`

    return {
      requirement,
      status,
      evidence,
      recommendation,
      files: best.files,
    }
  }

  function deepTypes(req: string): ("auth" | "database" | "api" | "frontend" | "testing" | "security" | "deployment" | "ci-cd")[] {
    const map: ["auth" | "database" | "api" | "frontend" | "testing" | "security" | "deployment" | "ci-cd", RegExp][] = [
      ["auth", /\bauth|login|register|session|oauth|jwt\b/i],
      ["database", /\bdatabase|\bdb\b|schema|migration|sql|orm\b/i],
      ["api", /\bapi\b|endpoint|route|controller|rest|graphql/i],
      ["frontend", /frontend|\bui\b|component|page|view|react|vue|svelte|angular/i],
      ["testing", /\btest|testing|spec|coverage|unit|integration\b/i],
      ["security", /security|vulnerability|xss|csrf|injection|owasp/i],
      ["deployment", /deploy|docker|container|kubernetes|k8s|terraform/i],
      ["ci-cd", /\bci\b|\bcd\b|workflow|pipeline|github actions|gitlab/i],
    ]
    return map.filter((row) => row[1].test(req)).map((row) => row[0])
  }

  function convertAnalysis(analysis: Awaited<ReturnType<typeof AuditorAnalysis.analyzeCodebase>>): AllPatterns {
    const rows: AllPatterns = {
      auth: { found: false, details: [], files: [], metadata: {} },
      database: { found: false, details: [], files: [], metadata: {} },
      api: { found: false, details: [], files: [], metadata: {} },
      frontend: { found: false, details: [], files: [], metadata: {} },
      testing: { found: false, details: [], files: [], metadata: {} },
      cicd: { found: false, details: [], files: [], metadata: {} },
      docker: { found: false, details: [], files: [], metadata: {} },
      security: { found: false, details: [], files: [], metadata: {} },
      docs: { found: false, details: [], files: [], metadata: {} },
      general: { codeFiles: analysis.files, totalLines: 0 },
    }

    for (const row of analysis.patterns) {
      const extra = [`confidence ${row.confidence}%`, `completeness ${row.completeness}%`]
      if (row.type === "auth") rows.auth = { found: row.found, details: [...row.details, ...extra], files: row.files, metadata: {} }
      if (row.type === "database") rows.database = { found: row.found, details: [...row.details, ...extra], files: row.files, metadata: {} }
      if (row.type === "api") rows.api = { found: row.found, details: [...row.details, ...extra], files: row.files, metadata: {} }
      if (row.type === "frontend") rows.frontend = { found: row.found, details: [...row.details, ...extra], files: row.files, metadata: {} }
      if (row.type === "testing") rows.testing = { found: row.found, details: [...row.details, ...extra], files: row.files, metadata: {} }
      if (row.type === "security") rows.security = { found: row.found, details: [...row.details, ...extra], files: row.files, metadata: {} }
      if (row.type === "deployment") rows.docker = { found: row.found, details: [...row.details, ...extra], files: row.files, metadata: {} }
      if (row.type === "ci-cd") rows.cicd = { found: row.found, details: [...row.details, ...extra], files: row.files, metadata: {} }
    }

    return rows
  }

  function generateFixTask(finding: AuditorFinding, type: "missing" | "partial", index: number): string {
    const icon = type === "missing" ? "❌" : "⚠️"
    const priority = type === "missing" ? "HIGH" : "MEDIUM"
    
    return `### ${icon} Task ${index}: ${finding.requirement}

**Type:** ${type.toUpperCase()}
**Priority:** ${priority}
**Status:** ${finding.status}

**Current Evidence:**
${finding.evidence}

**Recommendation:**
${finding.recommendation}

${finding.files && finding.files.length > 0 ? `**Related Files:**
${finding.files.map(f => `- ${f}`).join("\n")}
` : ""}**Acceptance Criteria:**
- [ ] Requirement is fully implemented
- [ ] Code follows project conventions
- [ ] Tests added (if applicable)
- [ ] Documentation updated

---
`
  }

  function generateIndividualTask(finding: AuditorFinding, index: number): string {
    return `# Fix Task ${index}

## Requirement
${finding.requirement}

## Current Status
- **Status:** ${finding.status}
- **Evidence:** ${finding.evidence}

## Goal
${finding.status === "missing" ? "Implement this requirement from scratch" : "Complete the partial implementation"}

## Recommendation
${finding.recommendation}

${finding.files && finding.files.length > 0 ? `## Related Files
${finding.files.map(f => `- ${f}`).join("\n")}
` : ""}## Implementation Steps

1. **Analyze Requirement**
   - Understand what needs to be built
   - Check existing codebase for patterns
   - Identify integration points

2. **Implement Solution**
   - Follow existing code conventions
   - Use established patterns
   - Handle edge cases

3. **Add Tests**
   - Unit tests for new functionality
   - Integration tests if applicable
   - Edge case coverage

4. **Verify**
   - Run existing tests
   - Manual verification
   - Check for regressions

## Context
This task was generated by the Pakalon Auditor after scanning the codebase.
The auditor detected that this requirement is ${finding.status}.

---
*Task ${index} - Generated ${new Date().toISOString()}*
`
  }
}
