import { mkdir } from "fs/promises"
import path from "path"
import { Filesystem } from "../util/filesystem"
import { Log } from "../util/log"
import { Pakalon } from "../pakalon"
import type { PhaseNumber } from "../pakalon"

const log = Log.create({ service: "pipeline:files" })

const PHASE_DIRS: Record<number, string[]> = {
  1: [
    "context_management.md",
    "plan.md",
    "tasks.md",
    "design.md",
    "phase-1.md",
    "agent-skills.md",
    "prd.md",
    "Database_schema.md",
    "API_reference.md",
    "risk-assessment.md",
    "user-stories.md",
    "technical-spec.md",
    "competitive-analysis.md",
    "constraints-and-tradeoffs.md",
  ],
  2: ["phase-2.md", "tdd-screenshots"],
  3: [
    "auditor.md",
    "subagent-1.md",
    "subagent-2.md",
    "subagent-3.md",
    "subagent-4.md",
    "subagent-5.md",
    "execution_log.md",
    "test-evidence",
  ],
  4: [
    "subagent-1.md",
    "subagent-2.md",
    "subagent-3.md",
    "subagent-4.md",
    "subagent-5.md",
  ],
  5: ["phase-5.md"],
  6: ["phase-6.md"],
}

export namespace FileStructure {
  export async function createPakalonAgents(projectPath: string): Promise<string> {
    const base = path.join(projectPath, Pakalon.DIR_AGENTS)
    const dirs = [
      base,
      path.join(base, "ai-agents"),
      path.join(base, "mcp-servers"),
      path.join(base, "wireframes"),
    ]

    for (let i = 1; i <= 6; i++) {
      dirs.push(path.join(base, "ai-agents", `phase-${i}`))
    }

    for (const dir of dirs) {
      await mkdir(dir, { recursive: true })
    }

    for (const [phase, items] of Object.entries(PHASE_DIRS)) {
      const phaseDir = path.join(base, "ai-agents", `phase-${phase}`)
      for (const item of items) {
        const itemPath = path.join(phaseDir, item)
        if (item.includes(".")) {
          await Filesystem.write(itemPath, "")
        } else {
          await mkdir(itemPath, { recursive: true })
        }
      }
    }

    await Filesystem.write(
      path.join(base, "pakalon.db"),
      "",
    )

    const syncContent = `// Pakalon sync module
// This file manages synchronization between phases and agents
export const version = "1.0.0"
export const phases = [1, 2, 3, 4, 5, 6]
`
    await Filesystem.write(path.join(base, "ai-agents", "sync.js"), syncContent)

    log.info("created pakalon-agents structure", { base })
    return base
  }

  export async function createPakalonNormal(projectPath: string): Promise<string> {
    const base = path.join(projectPath, Pakalon.DIR_NORMAL)
    const dirs = [base, path.join(base, "agents")]

    for (const dir of dirs) {
      await mkdir(dir, { recursive: true })
    }

    const projectName = path.basename(projectPath)
    const timestamp = new Date().toISOString()

    const files = [
      {
        path: "plan.md",
        content: `# Project Plan

## Project: ${projectName}
**Created:** ${timestamp}
**Mode:** Normal (Non-Pipeline)

## Overview
This project uses Pakalon's normal mode for development assistance.

## Goals
- [ ] Define project requirements
- [ ] Set up development environment
- [ ] Implement core features
- [ ] Add tests and documentation
- [ ] Deploy to production

## Tech Stack
- **Frontend:** TBD
- **Backend:** TBD
- **Database:** TBD
- **Deployment:** TBD

## Milestones
1. **Week 1:** Project setup and planning
2. **Week 2-3:** Core development
3. **Week 4:** Testing and refinement
4. **Week 5:** Deployment and documentation

## Notes
- Use /plan to enter planning mode
- Use /build to start development
- Use /auditor to check completeness

---
*Generated by Pakalon*
`,
      },
      {
        path: "task.md",
        content: `# Task Breakdown

## Setup Tasks
- [ ] Initialize project structure
- [ ] Configure development tools
- [ ] Set up version control

## Development Tasks
- [ ] Implement core functionality
- [ ] Add user interface
- [ ] Integrate backend services
- [ ] Add error handling

## Testing Tasks
- [ ] Write unit tests
- [ ] Write integration tests
- [ ] Perform manual testing

## Documentation Tasks
- [ ] Write README
- [ ] Document API
- [ ] Create user guide

## Deployment Tasks
- [ ] Configure CI/CD
- [ ] Set up production environment
- [ ] Deploy application

---
*Generated by Pakalon*
`,
      },
      {
        path: "user-stories.md",
        content: `# User Stories

## Epic 1: User Authentication

### US-001: User Registration
**As a** new user
**I want to** create an account
**So that** I can access the application

**Acceptance Criteria:**
- [ ] User can register with email and password
- [ ] Email validation is performed
- [ ] Password meets security requirements
- [ ] User receives confirmation

### US-002: User Login
**As a** registered user
**I want to** login to my account
**So that** I can access my data

**Acceptance Criteria:**
- [ ] User can login with credentials
- [ ] JWT token is returned
- [ ] Invalid credentials show error

## Epic 2: Core Functionality

### US-003: Main Feature
**As a** user
**I want to** use the main feature
**So that** I can accomplish my goals

**Acceptance Criteria:**
- [ ] Feature works as expected
- [ ] User receives feedback
- [ ] Data is persisted

---
*Generated by Pakalon*
`,
      },
      {
        path: "context-management.md",
        content: `# Context Management

## Token Budget Allocation

### Total Budget
- **Total Tokens:** 200,000
- **Buffer:** 10% (20,000 tokens)
- **Available:** 180,000 tokens

### Phase Allocation
| Phase | Allocated | Purpose |
|-------|-----------|---------|
| Planning | 30,000 | Requirements and design |
| Development | 100,000 | Code implementation |
| Testing | 30,000 | Test creation and execution |
| Documentation | 20,000 | Docs and guides |

### Best Practices
1. Keep context focused on current task
2. Summarize completed work
3. Clear context between phases
4. Monitor token usage

### Context Window Usage
- **Current:** 0%
- **Remaining:** 100%
- **Status:** Ready

---
*Generated by Pakalon*
`,
      },
      {
        path: path.join("agents", "skills.md"),
        content: `# Agent Skills

## Available Skills

### Development Skills
- **Code Generation** - Write and modify code
- **Debugging** - Find and fix bugs
- **Refactoring** - Improve code quality
- **Testing** - Write and run tests

### Documentation Skills
- **README Generation** - Create project documentation
- **API Documentation** - Document endpoints
- **User Guides** - Create user documentation

### DevOps Skills
- **CI/CD Setup** - Configure pipelines
- **Docker** - Container configuration
- **Deployment** - Deploy applications

## Skill Usage

### Automatic Skills
These skills are automatically available:
- File reading and writing
- Code search and analysis
- Git operations
- Package management

### Custom Skills
Add custom skills to \`.pakalon/agents/skills.md\`:
\`\`\`markdown
## Custom Skill: [Name]
**Description:** What this skill does
**Usage:** How to use it
**Examples:** Example invocations
\`\`\`

## Recommended Skills by Project Type

### Web Application
- React/Next.js best practices
- Tailwind CSS components
- API design patterns

### CLI Tool
- Command-line argument parsing
- Error handling patterns
- Help documentation

### Library
- API design
- Documentation generation
- Testing strategies

---
*Generated by Pakalon*
`,
      },
    ]

    for (const f of files) {
      await Filesystem.write(path.join(base, f.path), f.content)
    }

    log.info("created .pakalon structure", { base })
    return base
  }

  export async function ensurePhaseDir(projectPath: string, phase: PhaseNumber): Promise<string> {
    const dir = Pakalon.phaseDir(projectPath, phase)
    await mkdir(dir, { recursive: true })
    return dir
  }

  export async function writeArtifact(
    projectPath: string,
    phase: PhaseNumber,
    name: string,
    content: string,
  ): Promise<string> {
    const dir = await ensurePhaseDir(projectPath, phase)
    const p = path.join(dir, name)
    await Filesystem.write(p, content)
    log.info("wrote artifact", { phase, name, path: p })
    return p
  }

  export async function readArtifact(
    projectPath: string,
    phase: PhaseNumber,
    name: string,
  ): Promise<string | undefined> {
    const dir = Pakalon.phaseDir(projectPath, phase)
    const p = path.join(dir, name)
    try {
      return await Filesystem.readText(p)
    } catch {
      return undefined
    }
  }

  export async function listArtifacts(projectPath: string, phase: PhaseNumber): Promise<string[]> {
    const dir = Pakalon.phaseDir(projectPath, phase)
    try {
      const { readdir } = await import("fs/promises")
      const entries = await readdir(dir, { withFileTypes: true })
      return entries.filter((e) => e.isFile()).map((e) => e.name)
    } catch {
      return []
    }
  }

  export async function exists(projectPath: string): Promise<boolean> {
    const agentsPath = path.join(projectPath, Pakalon.DIR_AGENTS)
    return Filesystem.exists(agentsPath)
  }

  export async function existsNormal(projectPath: string): Promise<boolean> {
    const normalPath = path.join(projectPath, Pakalon.DIR_NORMAL)
    return Filesystem.exists(normalPath)
  }
}
