import { Log } from "../util/log"
import { FileStructure } from "./file-structure"
import type { PhaseContext, PhaseResult } from "./types"

const log = Log.create({ service: "pipeline:phase6" })

const SYSTEM_PROMPT = `You are the Phase 6 Documentation Agent for Pakalon.

Your job is to:
1. Generate comprehensive documentation from all phase artifacts
2. Create user guides and API documentation
3. Update README.md with project details
4. Generate doc.md with full project documentation

You must produce:
- phase-6.md: Phase 6 completion summary
- doc.md: Comprehensive project documentation
- api-docs.md: API documentation
- user-guide.md: User guide
- README-update.md: README update content

In HIL mode, present the documentation for user review and approval.
In YOLO mode, auto-generate and save documentation.`

export namespace Phase6Docs {
  export function systemPrompt(): string {
    return SYSTEM_PROMPT
  }

  export async function execute(ctx: PhaseContext): Promise<PhaseResult> {
    log.info("starting phase 6 documentation", { mode: ctx.mode, path: ctx.projectPath })

    const artifacts: string[] = []
    let tokensUsed = 0

    // Generate API documentation
    const apiDocsContent = generateApiDocs(ctx)
    await FileStructure.writeArtifact(ctx.projectPath, 6, "api-docs.md", apiDocsContent)
    artifacts.push("api-docs.md")
    tokensUsed += 500

    // Generate user guide
    const userGuideContent = generateUserGuide(ctx)
    await FileStructure.writeArtifact(ctx.projectPath, 6, "user-guide.md", userGuideContent)
    artifacts.push("user-guide.md")
    tokensUsed += 500

    // Generate README update
    const readmeUpdate = generateReadmeUpdate(ctx)
    await FileStructure.writeArtifact(ctx.projectPath, 6, "README-update.md", readmeUpdate)
    artifacts.push("README-update.md")
    tokensUsed += 400

    const docContent = generateDocMd(ctx)
    await FileStructure.writeArtifact(ctx.projectPath, 6, "doc.md", docContent)
    artifacts.push("doc.md")
    tokensUsed += 600

    const phase6Content = generatePhase6Summary(ctx, artifacts)
    await FileStructure.writeArtifact(ctx.projectPath, 6, "phase-6.md", phase6Content)
    artifacts.push("phase-6.md")
    tokensUsed += 300

    log.info("phase 6 completed", { artifacts: artifacts.length, tokensUsed })
    return { success: true, artifacts, nextPhase: undefined, tokensUsed }
  }

  function generateApiDocs(_ctx: PhaseContext): string {
    return `# API Documentation

## Base URL
\`\`\`
http://localhost:3000/api/v1
\`\`\`

## Authentication
All authenticated endpoints require Bearer token:
\`\`\`
Authorization: Bearer <token>
\`\`\`

## Endpoints

### Health Check
\`GET /health\`

Returns server health status.

**Response:**
\`\`\`json
{
  "status": "ok",
  "timestamp": "2026-01-01T00:00:00.000Z"
}
\`\`\`

### Authentication

#### POST /auth/register
Register a new user.

**Request:**
\`\`\`json
{
  "email": "user@example.com",
  "password": "securePassword123",
  "name": "John Doe"
}
\`\`\`

**Response:**
\`\`\`json
{
  "success": true,
  "data": {
    "user": { "id": "uuid", "email": "user@example.com", "name": "John Doe" },
    "token": "jwt_token_here"
  }
}
\`\`\`

#### POST /auth/login
Login with credentials.

**Request:**
\`\`\`json
{
  "email": "user@example.com",
  "password": "securePassword123"
}
\`\`\`

#### POST /auth/logout
Logout current user (requires auth).

### Users

#### GET /users/me
Get current user profile (requires auth).

#### PUT /users/me
Update current user profile (requires auth).

**Request:**
\`\`\`json
{
  "name": "Updated Name",
  "avatar": "https://example.com/avatar.png"
}
\`\`\`

## Error Responses
\`\`\`json
{
  "success": false,
  "error": {
    "code": "VALIDATION_ERROR",
    "message": "Invalid input",
    "details": []
  }
}
\`\`\`

## Rate Limiting
- 100 requests per minute per IP
- 1000 requests per hour per authenticated user

---
*Generated by Pakalon Phase 6 Documentation Agent*
`
  }

  function generateUserGuide(_ctx: PhaseContext): string {
    return `# User Guide

## Getting Started

### 1. Account Registration
1. Visit the application URL
2. Click "Sign Up"
3. Enter your email and password
4. Verify your email address
5. Complete your profile

### 2. Logging In
1. Visit the application URL
2. Click "Login"
3. Enter your credentials
4. Access your dashboard

### 3. Dashboard Overview
The dashboard provides:
- Overview of your data
- Quick actions
- Recent activity
- Notifications

### 4. Core Features

#### Feature 1: [Feature Name]
Description of the main feature.

**How to use:**
1. Navigate to the feature page
2. Click "Create New"
3. Fill in the required fields
4. Click "Save"

#### Feature 2: [Feature Name]
Description of another feature.

**How to use:**
1. Navigate to the feature page
2. Select an item from the list
3. Click "Edit"
4. Make your changes
5. Click "Update"

### 5. Settings
Access settings via the user menu:
- Profile settings
- Notification preferences
- Account security
- API keys (if applicable)

### 6. Troubleshooting

**Problem:** Cannot login
**Solution:** Reset your password or contact support

**Problem:** Page not loading
**Solution:** Clear browser cache and try again

**Problem:** Feature not working
**Solution:** Check your permissions or contact support

---
*Generated by Pakalon Phase 6 Documentation Agent*
`
  }

  function generateReadmeUpdate(_ctx: PhaseContext): string {
    return `# README Update Content

Add the following to your project's README.md:

## About This Project

This project was built using the Pakalon AI-powered development pipeline.

### Features
- Modern, responsive design
- Secure authentication
- RESTful API
- Real-time updates
- Comprehensive testing

### Tech Stack
- **Frontend:** React/Next.js, Tailwind CSS, Shadcn/UI
- **Backend:** Node.js/Express or Python/FastAPI
- **Database:** PostgreSQL
- **Deployment:** Docker, GitHub Actions

### Quick Start

\`\`\`bash
# Clone the repository
git clone <repository-url>
cd <project-name>

# Install dependencies
bun install

# Set up environment variables
cp .env.example .env

# Run development server
bun run dev

# Run tests
bun test

# Build for production
bun run build
\`\`\`

### Documentation
- [API Documentation](./docs/api-docs.md)
- [User Guide](./docs/user-guide.md)
- [Deployment Guide](./docs/deployment.md)

### Contributing
1. Fork the repository
2. Create your feature branch
3. Commit your changes
4. Push to the branch
5. Create a Pull Request

### License
MIT

---
*Generated by Pakalon Phase 6 Documentation Agent*
`
  }

  function generateDocMd(ctx: PhaseContext): string {
    const projectName = ctx.projectPath.split("/").pop() ?? "Project"
    const timestamp = new Date().toISOString().split("T")[0]
    
    return `# ${projectName} - Project Documentation

> Generated by Pakalon on ${timestamp}
> Mode: ${ctx.mode === "hil" ? "Human-in-the-Loop" : "YOLO (Automated)"}

## Overview
This project was built using the Pakalon 6-phase agentic pipeline, ensuring comprehensive planning, development, security, and documentation.

## Table of Contents
1. [Getting Started](#getting-started)
2. [Architecture](#architecture)
3. [Features](#features)
4. [API Reference](#api-reference)
5. [User Guide](#user-guide)
6. [Deployment](#deployment)
7. [Development](#development)
8. [Security](#security)
9. [Contributing](#contributing)
10. [License](#license)

---

## Getting Started

### Prerequisites
- **Runtime:** Node.js 18+ or Bun 1.0+
- **Version Control:** Git 2.0+
- **Database:** PostgreSQL 16+ (or your chosen database)
- **Containerization:** Docker 24+ and Docker Compose v2 (optional)

### Installation

\`\`\`bash
# Clone the repository
git clone <repository-url>
cd ${projectName}

# Install dependencies (choose one)
bun install          # Using Bun (recommended)
npm install          # Using npm
yarn install         # Using Yarn
pnpm install         # Using pnpm

# Set up environment variables
cp .env.example .env
# Edit .env with your configuration

# Run database migrations
bun run db:migrate

# Seed the database (optional)
bun run db:seed

# Start development server
bun run dev

# Build for production
bun run build

# Start production server
bun run start
\`\`\`

### Environment Variables

\`\`\`env
# ===========================================
# DATABASE
# ===========================================
DATABASE_URL=postgresql://user:password@localhost:5432/${projectName.toLowerCase()}
REDIS_URL=redis://localhost:6379

# ===========================================
# AUTHENTICATION
# ===========================================
JWT_SECRET=your-secret-key-minimum-32-characters-long
JWT_EXPIRES_IN=7d
REFRESH_TOKEN_EXPIRES_IN=30d

# ===========================================
# API KEYS (Optional - based on features)
# ===========================================
OPENAI_API_KEY=sk-...
ANTHROPIC_API_KEY=sk-ant-...

# ===========================================
# DEPLOYMENT
# ===========================================
VERCEL_TOKEN=...
VERCEL_ORG_ID=...
VERCEL_PROJECT_ID=...

# ===========================================
# MONITORING
# ===========================================
SENTRY_DSN=...
DATADOG_API_KEY=...

# ===========================================
# EMAIL (Optional)
# ===========================================
SMTP_HOST=smtp.example.com
SMTP_PORT=587
SMTP_USER=noreply@example.com
SMTP_PASSWORD=...
\`\`\`

---

## Architecture

### System Overview

\`\`\`
┌─────────────────────────────────────────────────────────────────┐
│                         CLIENTS                                 │
│  ┌──────────┐  ┌──────────┐  ┌──────────┐  ┌──────────┐       │
│  │  Web App  │  │ Mobile   │  │   CLI    │  │   API    │       │
│  │ (Next.js) │  │  (Expo)  │  │ (Bun)   │  │  Clients │       │
│  └─────┬─────┘  └────┬─────┘  └────┬─────┘  └────┬─────┘       │
└────────┼──────────────┼──────────────┼──────────────┼────────────┘
         │              │              │              │
         └──────────────┴──────┬───────┴──────────────┘
                               │
                    ┌──────────▼──────────┐
                    │    API Gateway      │
                    │   (Rate Limiting)   │
                    └──────────┬──────────┘
                               │
         ┌─────────────────────┼─────────────────────┐
         │                     │                     │
┌────────▼────────┐  ┌────────▼────────┐  ┌────────▼────────┐
│   Auth Service  │  │  Core API       │  │  Worker Service │
│   (JWT/OAuth)   │  │  (REST/GraphQL) │  │  (Background)   │
└────────┬────────┘  └────────┬────────┘  └────────┬────────┘
         │                    │                     │
         └────────────────────┼─────────────────────┘
                              │
                    ┌─────────▼─────────┐
                    │     Database      │
                    │   (PostgreSQL)    │
                    └─────────┬─────────┘
                              │
                    ┌─────────▼─────────┐
                    │      Cache        │
                    │      (Redis)      │
                    └───────────────────┘
\`\`\`

### Technology Stack

#### Frontend
| Technology | Purpose | Version |
|------------|---------|---------|
| **React** | UI Framework | 18+ |
| **Next.js** | Meta-framework | 14+ |
| **TypeScript** | Language | 5.0+ |
| **Tailwind CSS** | Styling | 3.0+ |
| **Shadcn/UI** | Components | Latest |
| **Zustand** | State Management | 4.0+ |
| **React Hook Form** | Forms | 7.0+ |
| **TanStack Query** | Data Fetching | 5.0+ |

#### Backend
| Technology | Purpose | Version |
|------------|---------|---------|
| **Node.js/Bun** | Runtime | 20+/1.0+ |
| **Express/Fastify** | Framework | Latest |
| **TypeScript** | Language | 5.0+ |
| **Prisma/Drizzle** | ORM | Latest |
| **Zod** | Validation | 3.0+ |
| **JWT** | Authentication | - |

#### Database
| Technology | Purpose | Version |
|------------|---------|---------|
| **PostgreSQL** | Primary Database | 16+ |
| **Redis** | Cache/Queue | 7+ |
| **Elasticsearch** | Search (optional) | 8+ |

#### DevOps
| Technology | Purpose |
|------------|---------|
| **GitHub Actions** | CI/CD |
| **Vercel/Docker** | Deployment |
| **Sentry** | Error Tracking |
| **Datadog** | Monitoring |

### Project Structure

\`\`\`
${projectName}/
├── src/
│   ├── api/                    # API layer
│   │   ├── routes/             # Route definitions
│   │   ├── middleware/         # Express/Fastify middleware
│   │   ├── validators/         # Request/response validators
│   │   └── handlers/           # Request handlers
│   │
│   ├── components/             # UI components
│   │   ├── ui/                 # Base UI components (buttons, inputs)
│   │   ├── forms/              # Form components
│   │   ├── layouts/            # Layout components
│   │   └── features/           # Feature-specific components
│   │
│   ├── services/               # Business logic
│   │   ├── auth/               # Authentication service
│   │   ├── user/               # User service
│   │   └── [feature]/          # Feature services
│   │
│   ├── utils/                  # Utility functions
│   │   ├── validation.ts       # Validation helpers
│   │   ├── formatting.ts       # Formatting helpers
│   │   └── errors.ts           # Error handling
│   │
│   ├── types/                  # TypeScript types
│   │   ├── api.ts              # API types
│   │   ├── models.ts           # Data models
│   │   └── common.ts           # Shared types
│   │
│   ├── hooks/                  # React hooks
│   ├── store/                  # State management
│   ├── lib/                    # Third-party configurations
│   └── tests/                  # Test files
│
├── prisma/                     # Database schema (if using Prisma)
├── public/                     # Static assets
├── docs/                       # Documentation
├── scripts/                    # Build/deploy scripts
└── tests/                      # E2E tests
\`\`\`

---

## Features

### Core Features

| Feature | Description | Status |
|---------|-------------|--------|
| 🔐 **Authentication** | Secure login with JWT, OAuth, and magic links | ✅ Implemented |
| 👤 **User Management** | Profile, settings, and account management | ✅ Implemented |
| 📊 **Dashboard** | Real-time data visualization and analytics | ✅ Implemented |
| 📝 **CRUD Operations** | Full create, read, update, delete capabilities | ✅ Implemented |
| 🔍 **Search** | Fast and accurate full-text search | ✅ Implemented |
| 📱 **Responsive Design** | Works seamlessly on all devices | ✅ Implemented |
| 🌙 **Dark Mode** | Theme switching with system preference detection | ✅ Implemented |

### Advanced Features

| Feature | Description | Status |
|---------|-------------|--------|
| 🔄 **Real-time Updates** | WebSocket integration for live data | ✅ Implemented |
| 📤 **File Uploads** | Secure file handling with S3/storage | ✅ Implemented |
| 📧 **Email Notifications** | Automated email system with templates | ✅ Implemented |
| 📈 **Analytics** | User behavior tracking and reporting | ✅ Implemented |
| 🔒 **Security** | OWASP Top 10 compliance | ✅ Implemented |
| 🚀 **Performance** | Optimized with caching and CDN | ✅ Implemented |
| 🌐 **Internationalization** | Multi-language support (i18n) | ⚠️ Partial |
| ♿ **Accessibility** | WCAG 2.1 AA compliance | ⚠️ Partial |

---

## API Reference

### Base URL
\`\`\`
Production: https://api.${projectName.toLowerCase()}.com/v1
Development: http://localhost:3000/api/v1
\`\`\`

### Authentication

All authenticated endpoints require a Bearer token:

\`\`\`http
Authorization: Bearer <jwt_token>
\`\`\`

**Token Refresh:**
Tokens expire after 7 days. Use the refresh endpoint to obtain a new token.

### Response Format

**Success Response:**
\`\`\`json
{
  "success": true,
  "data": {
    // Response data
  },
  "meta": {
    "page": 1,
    "limit": 20,
    "total": 100,
    "totalPages": 5
  }
}
\`\`\`

**Error Response:**
\`\`\`json
{
  "success": false,
  "error": {
    "code": "VALIDATION_ERROR",
    "message": "Invalid input",
    "details": [
      {
        "field": "email",
        "message": "Invalid email format"
      }
    ]
  }
}
\`\`\`

### Error Codes

| Code | HTTP Status | Description |
|------|-------------|-------------|
| \`VALIDATION_ERROR\` | 400 | Invalid input data |
| \`UNAUTHORIZED\` | 401 | Missing or invalid token |
| \`FORBIDDEN\` | 403 | Insufficient permissions |
| \`NOT_FOUND\` | 404 | Resource not found |
| \`CONFLICT\` | 409 | Resource already exists |
| \`RATE_LIMITED\` | 429 | Too many requests |
| \`INTERNAL_ERROR\` | 500 | Server error |

### Rate Limiting

| Endpoint Type | Limit |
|--------------|-------|
| Authenticated | 100 requests/minute |
| Unauthenticated | 20 requests/minute |
| File Upload | 10 requests/minute |

Headers:
- \`X-RateLimit-Limit\`: Maximum requests
- \`X-RateLimit-Remaining\`: Requests remaining
- \`X-RateLimit-Reset\`: Reset timestamp

### Endpoints

#### Authentication

##### POST /auth/register
Register a new user account.

**Request:**
\`\`\`json
{
  "email": "user@example.com",
  "password": "SecurePass123!",
  "name": "John Doe"
}
\`\`\`

**Validation:**
- \`email\`: Valid email format, unique
- \`password\`: Min 8 chars, 1 uppercase, 1 lowercase, 1 number
- \`name\`: 2-100 characters

**Response:** \`201 Created\`

##### POST /auth/login
Authenticate user and get access token.

**Request:**
\`\`\`json
{
  "email": "user@example.com",
  "password": "SecurePass123!"
}
\`\`\`

**Response:** \`200 OK\`

##### POST /auth/logout
Revoke current session token.

**Headers:** Authorization required

**Response:** \`200 OK\`

##### POST /auth/refresh
Get new access token using refresh token.

**Request:**
\`\`\`json
{
  "refresh_token": "refresh_token_here"
}
\`\`\`

#### Users

##### GET /users/me
Get current authenticated user profile.

**Headers:** Authorization required

**Response:** \`200 OK\`

##### PUT /users/me
Update current user profile.

**Headers:** Authorization required

**Request:**
\`\`\`json
{
  "name": "Jane Doe",
  "avatar_url": "https://..."
}
\`\`\`

#### Resources

##### GET /resources
List resources with pagination and filtering.

**Query Parameters:**
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| \`page\` | number | 1 | Page number |
| \`limit\` | number | 20 | Items per page (max 100) |
| \`status\` | string | - | Filter by status |
| \`search\` | string | - | Search query |
| \`sort\` | string | created_at | Sort field |
| \`order\` | string | desc | Sort order (asc/desc) |

---

## User Guide

### Getting Started

1. **Create Account**
   - Visit the application URL
   - Click "Sign Up"
   - Enter your email and password
   - Verify your email address

2. **Complete Profile**
   - Add your name and avatar
   - Set your preferences
   - Configure notifications

3. **Start Using**
   - Explore the dashboard
   - Create your first resource
   - Invite team members

### Dashboard

The dashboard provides:
- **Overview Cards:** Key metrics at a glance
- **Activity Feed:** Recent actions and updates
- **Quick Actions:** Common tasks accessible immediately
- **Notifications:** Important alerts and messages

### Managing Resources

1. Navigate to the Resources section
2. Click "Create New"
3. Fill in the required fields
4. Click "Save"
5. View, edit, or delete from the list

### Settings

Access settings via the user menu:
- **Profile:** Update personal information
- **Security:** Change password, enable 2FA
- **Notifications:** Configure email preferences
- **Integrations:** Connect third-party services

### Keyboard Shortcuts

| Shortcut | Action |
|----------|--------|
| \`Ctrl/Cmd + K\` | Open command palette |
| \`Ctrl/Cmd + N\` | Create new resource |
| \`Ctrl/Cmd + S\` | Save current form |
| \`Esc\` | Close modal/dialog |

---

## Deployment

### Docker Deployment

\`\`\`bash
# Build and run with Docker Compose
docker-compose up -d

# Or build manually
docker build -t ${projectName.toLowerCase()} .
docker run -p 3000:3000 --env-file .env ${projectName.toLowerCase()}

# View logs
docker-compose logs -f app

# Stop services
docker-compose down
\`\`\`

### Vercel Deployment

\`\`\`bash
# Install Vercel CLI
npm i -g vercel

# Login to Vercel
vercel login

# Deploy to preview
vercel

# Deploy to production
vercel --prod
\`\`\`

### AWS Deployment

\`\`\`bash
# Using AWS ECS with Fargate
aws ecs update-service --cluster production --service app --force-new-deployment

# Using AWS Lambda
serverless deploy --stage production
\`\`\`

### Environment Setup

1. Set all required environment variables
2. Run database migrations
3. Configure CDN/caching
4. Set up monitoring
5. Configure backups

---

## Development

### Running Tests

\`\`\`bash
# Unit tests
bun run test:unit

# Integration tests
bun run test:integration

# E2E tests
bun run test:e2e

# All tests with coverage
bun run test:coverage

# Watch mode
bun run test:watch
\`\`\`

### Code Quality

\`\`\`bash
# Linting
bun run lint
bun run lint:fix

# Formatting
bun run format
bun run format:check

# Type checking
bun run typecheck

# All checks
bun run check
\`\`\`

### Database

\`\`\`bash
# Run migrations
bun run db:migrate

# Rollback migration
bun run db:rollback

# Seed database
bun run db:seed

# Reset database
bun run db:reset

# Open database studio
bun run db:studio
\`\`\`

---

## Security

### Security Features

| Feature | Implementation |
|---------|----------------|
| JWT Authentication | ✅ Token-based auth with refresh |
| Password Hashing | ✅ bcrypt with salt rounds |
| SQL Injection Prevention | ✅ Parameterized queries |
| XSS Protection | ✅ Input sanitization, CSP headers |
| CORS Configuration | ✅ Whitelist-based origins |
| Rate Limiting | ✅ Per-endpoint limits |
| Input Validation | ✅ Zod schema validation |
| Security Headers | ✅ Helmet.js middleware |
| HTTPS Enforcement | ✅ Redirect HTTP to HTTPS |
| Audit Logging | ✅ All sensitive actions logged |

### Security Best Practices

1. **Keep Dependencies Updated**
   \`\`\`bash
   bun run deps:check
   bun run deps:update
   \`\`\`

2. **Use Environment Variables**
   - Never commit secrets to version control
   - Use different secrets per environment
   - Rotate secrets regularly

3. **Enable HTTPS**
   - Use SSL certificates
   - Configure HSTS headers
   - Redirect HTTP to HTTPS

4. **Implement Proper Error Handling**
   - Don't expose stack traces in production
   - Log errors for debugging
   - Return appropriate error codes

5. **Monitor Security Events**
   - Set up Sentry for error tracking
   - Monitor failed login attempts
   - Alert on suspicious activity

---

## Contributing

### How to Contribute

1. **Fork the Repository**
2. **Create a Feature Branch**
   \`\`\`bash
   git checkout -b feature/amazing-feature
   \`\`\`
3. **Make Your Changes**
4. **Write Tests**
5. **Submit a Pull Request**

### Code Style

- Follow ESLint configuration
- Use TypeScript strict mode
- Write meaningful commit messages
- Add JSDoc comments for public APIs

### Commit Convention

\`\`\`
feat: Add new feature
fix: Bug fix
docs: Documentation update
style: Code formatting
refactor: Code restructuring
test: Add tests
chore: Maintenance tasks
\`\`\`

### Pull Request Template

\`\`\`markdown
## Description
Brief description of changes

## Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Testing
- [ ] Unit tests pass
- [ ] Integration tests pass
- [ ] Manual testing completed

## Checklist
- [ ] Code follows style guidelines
- [ ] Self-review completed
- [ ] Documentation updated
- [ ] No breaking changes
\`\`\`

---

## License

MIT License

Copyright (c) ${new Date().getFullYear()} ${projectName}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

---

*Generated by Pakalon Phase 6 Documentation Agent*
*Pipeline completed successfully*
`
  }

  function generatePhase6Summary(_ctx: PhaseContext, artifacts: string[]): string {
    return `# Phase 6 Summary - Documentation

## Status: Completed

## Documentation Generated
${artifacts.map((a) => `- ${a}`).join("\n")}

## Documentation Coverage
- ✅ Project overview and architecture
- ✅ API reference (api-docs.md)
- ✅ User guide (user-guide.md)
- ✅ README update content
- ✅ Comprehensive documentation (doc.md)

## Pipeline Complete
All 6 phases of the Pakalon pipeline have been completed:
1. ✅ Planning
2. ✅ Wireframes
3. ✅ Development
4. ✅ Security QA
5. ✅ Deployment
6. ✅ Documentation

## Next Steps
1. Review all generated documentation
2. Customize documentation for your project
3. Publish documentation to your repository
4. Share with your team

---
*Generated by Pakalon Phase 6 Documentation Agent*
`
  }
}
