id = "pakalon"
name = "Pakalon"
description = "The open source coding agent."
version = "1.2.27"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/pakalon"

[agent_servers.pakalon]
name = "Pakalon"
icon = "./icons/pakalon.svg"

[agent_servers.pakalon.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/pakalon/releases/download/v1.2.27/pakalon-darwin-arm64.zip"
cmd = "./pakalon"
args = ["acp"]

[agent_servers.pakalon.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/pakalon/releases/download/v1.2.27/pakalon-darwin-x64.zip"
cmd = "./pakalon"
args = ["acp"]

[agent_servers.pakalon.targets.linux-aarch64]
archive = "https://github.com/anomalyco/pakalon/releases/download/v1.2.27/pakalon-linux-arm64.tar.gz"
cmd = "./pakalon"
args = ["acp"]

[agent_servers.pakalon.targets.linux-x86_64]
archive = "https://github.com/anomalyco/pakalon/releases/download/v1.2.27/pakalon-linux-x64.tar.gz"
cmd = "./pakalon"
args = ["acp"]

[agent_servers.pakalon.targets.windows-x86_64]
archive = "https://github.com/anomalyco/pakalon/releases/download/v1.2.27/pakalon-windows-x64.zip"
cmd = "./pakalon.exe"
args = ["acp"]
