/**
 * Pakalon file structure generator.
 *
 * Creates the .pakalon-agents/ directory structure for the 6-phase pipeline.
 */
import * as fs from "node:fs/promises";
import * as path from "node:path";
import type { AgentFiles } from "./types";

const PHASE_DIRS = ["phase-1", "phase-2", "phase-3", "phase-4", "phase-5", "phase-6"];

const PHASE_FILES: Record<number, string[]> = {
	1: [
		"context_management.md",
		"plan.md",
		"tasks.md",
		"design.md",
		"phase-1.md",
		"agent-skills.md",
		"prd.md",
		"Database_schema.md",
		"API_reference.md",
		"risk-assessment.md",
		"user-stories.md",
		"technical-spec.md",
		"competitive-analysis.md",
		"constraints-and-tradeoffs.md",
	],
	2: ["phase-2.md", "Wireframe_generated.svg", "Wireframe_generated.json", "Wireframe_generated.penpot"],
	3: [
		"auditor.md",
		"subagent-1.md",
		"subagent-2.md",
		"subagent-3.md",
		"subagent-4.md",
		"subagent-5.md",
		"execution_log.md",
	],
	4: [
		"subagent-1.md",
		"subagent-2.md",
		"subagent-3.md",
		"subagent-4.md",
		"subagent-5.md",
		"blackbox_testing.xml",
		"whitebox_testing.xml",
	],
	5: ["phase-5.md"],
	6: ["phase-6.md"],
};

/**
 * Create the .pakalon-agents directory structure.
 */
export async function createAgentFiles(projectPath: string, projectName: string): Promise<AgentFiles> {
	const agentDir = path.join(projectPath, ".pakalon-agents", "ai-agents");

	// Create base directories
	await fs.mkdir(agentDir, { recursive: true });
	await fs.mkdir(path.join(agentDir, "mcp-servers"), { recursive: true });
	await fs.mkdir(path.join(agentDir, "wireframes"), { recursive: true });

	// Create phase directories and files
	const phases: AgentFiles["phases"] = {};

	for (const [phaseNum, files] of Object.entries(PHASE_FILES)) {
		const phaseNum_ = Number(phaseNum);
		const phaseDir = path.join(agentDir, PHASE_DIRS[phaseNum_ - 1]);
		await fs.mkdir(phaseDir, { recursive: true });

		const createdFiles: string[] = [];
		for (const file of files) {
			const filePath = path.join(phaseDir, file);
			try {
				await fs.access(filePath);
			} catch {
				// File doesn't exist, create it
				await fs.writeFile(
					filePath,
					`# ${file.replace(/\.md$/, "")}\n\nCreated by Pakalon for project: ${projectName}\n`,
				);
			}
			createdFiles.push(filePath);
		}

		phases[phaseNum_] = {
			dir: phaseDir,
			files: createdFiles,
		};
	}

	// Create sync.js bridge (placeholder)
	const syncJsPath = path.join(agentDir, "sync.js");
	try {
		await fs.access(syncJsPath);
	} catch {
		await fs.writeFile(
			syncJsPath,
			`// Penpot sync bridge for ${projectName}\n// Generated by Pakalon\n\nmodule.exports = {\n  sync: async () => {\n    console.log("Sync not configured. Set PENPOT_HOST and PENPOT_API_TOKEN.");\n  }\n};\n`,
		);
	}

	return {
		agentDir,
		phases,
		syncJs: syncJsPath,
		mcpServers: path.join(agentDir, "mcp-servers"),
		wireframes: path.join(agentDir, "wireframes"),
		db: path.join(agentDir, "pakalon.db"),
	};
}

/**
 * Check if .pakalon-agents is initialized.
 */
export async function isInitialized(projectPath: string): Promise<boolean> {
	try {
		await fs.access(path.join(projectPath, ".pakalon-agents"));
		return true;
	} catch {
		return false;
	}
}

/**
 * Get the agent directory path.
 */
export function getAgentDir(projectPath: string): string {
	return path.join(projectPath, ".pakalon-agents", "ai-agents");
}

/**
 * Get a phase directory path.
 */
export function getPhaseDir(projectPath: string, phase: number): string {
	return path.join(getAgentDir(projectPath), PHASE_DIRS[phase - 1]);
}

/**
 * Get a phase file path.
 */
export function getPhaseFile(projectPath: string, phase: number, fileName: string): string {
	return path.join(getPhaseDir(projectPath, phase), fileName);
}
