export {
  AGENT_TOOL_NAME,
  LEGACY_AGENT_TOOL_NAME,
  AGENT_COLORS,
  ONE_SHOT_BUILTIN_AGENT_TYPES,
  ASYNC_AGENT_ALLOWED_TOOLS,
  ALL_AGENT_DISALLOWED_TOOLS,
  CUSTOM_AGENT_DISALLOWED_TOOLS,
  IN_PROCESS_TEAMMATE_ALLOWED_TOOLS,
  COORDINATOR_MODE_ALLOWED_TOOLS,
  FORK_SUBAGENT_TYPE,
  FORK_BOILERPLATE_TAG,
  FORK_DIRECTIVE_PREFIX,
} from '../constants.js';

export type { AgentColorName } from '../constants.js';