/**
 * Auditor agent for Phase 3 compliance checking.
 * Scans codebase vs phase-1 requirements and writes auditor.md.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { Auditor } from "@oh-my-pi/pakalon-auditor";
import { logger } from "@oh-my-pi/pi-utils";

const PHASE1_DIR = (cwd: string) => path.join(cwd, ".pakalon-agents", "ai-agents", "phase-1");
const PHASE3_DIR = (cwd: string) => path.join(cwd, ".pakalon-agents", "ai-agents", "phase-3");

export interface AuditResult {
	missing: string[];
	partial: string[];
	complete: string[];
	passRate: number;
	report?: {
		version: number;
		passRate: number;
		missing: number;
		partial: number;
		complete: number;
		recommendedNext: "do-nothing" | "implement-core" | "implement-all";
	};
}

export async function auditCodebase(cwd: string): Promise<AuditResult> {
	logger.info("Auditor scanning codebase", { cwd });

	const phase1Dir = PHASE1_DIR(cwd);
	if (!fs.existsSync(phase1Dir)) {
		return {
			missing: ["phase-1 directory not found — run /phase-1 first"],
			partial: [],
			complete: [],
			passRate: 0,
		};
	}

	const auditor = new Auditor();
	const result = await auditor.runAudit(cwd, {
		projectDir: cwd,
		mode: "YOLO",
		maxIterations: 10,
		phase1Dir,
		phase3Dir: PHASE3_DIR(cwd),
	});

	const missing = result.findings
		.filter(f => f.severity === "critical" || f.rule === "missing-feature" || f.rule === "missing-phase1-artifact")
		.map(f => `${f.file ? `${path.basename(f.file)}: ` : ""}${f.message}`);

	const partial = result.findings
		.filter(f => f.rule === "partial-feature" || f.severity === "medium")
		.map(f => `${f.file ? `${path.basename(f.file)}: ` : ""}${f.message}`);

	const complete = result.buckets.filter(b => b.status === "complete").flatMap(b => b.findings.map(f => f.message));

	const passRate =
		result.buckets.length > 0
			? Math.round((result.complete / (result.complete + result.partial + result.missing || 1)) * 100)
			: 0;

	logger.info("Auditor scan complete", { passRate, missing: result.missing, partial: result.partial });

	return {
		missing,
		partial,
		complete,
		passRate,
		report: {
			version: 1,
			passRate,
			missing: result.missing,
			partial: result.partial,
			complete: result.complete,
			recommendedNext: result.recommendedNext,
		},
	};
}

export function writeAuditorReport(cwd: string, result: AuditResult): void {
	const dir = path.join(cwd, ".pakalon-agents", "ai-agents", "phase-3");
	fs.mkdirSync(dir, { recursive: true });

	const lines: string[] = ["# Auditor Report", "", `## Pass Rate: ${result.passRate}%`, ""];

	if (result.missing.length > 0) {
		lines.push("## Missing Features", "");
		for (const item of result.missing) {
			lines.push(`- ${item}`);
		}
		lines.push("");
	} else {
		lines.push("## Missing Features", "", "None", "");
	}

	if (result.partial.length > 0) {
		lines.push("## Partially Implemented", "");
		for (const item of result.partial) {
			lines.push(`- ${item}`);
		}
		lines.push("");
	} else {
		lines.push("## Partially Implemented", "", "None", "");
	}

	if (result.complete.length > 0) {
		lines.push("## Fully Implemented", "");
		for (const item of result.complete) {
			lines.push(`- ${item}`);
		}
		lines.push("");
	}

	if (result.report) {
		lines.push("## Recommended Next Action", "");
		lines.push(
			result.report.recommendedNext === "implement-all"
				? "Implement all missing and partially implemented features"
				: result.report.recommendedNext === "implement-core"
					? "Implement core missing features"
					: "No further action needed",
		);
		lines.push("");
		lines.push("---", "*Generated by Pakalon Auditor Agent*");
	}

	fs.writeFileSync(path.join(dir, "auditor.md"), lines.join("\n"));
}
