/**
 * Phase 5: Git + GitHub + deploy orchestration.
 *
 * Initializes git, creates a commit, pushes to GitHub, then
 * prompts for a cloud target (AWS / DigitalOcean / Azure / GCP /
 * None) and writes the relevant workflow + Dockerfile.
 */
import * as fs from "node:fs";
import { logger } from "@oh-my-pi/pi-utils";

export type CloudTarget = "aws" | "digitalocean" | "azure" | "gcp" | "none";

export interface Phase5Context {
	projectDir: string;
	phase5Dir: string;
	repoFullName?: string; // e.g. "user/repo"
	cloudTarget: CloudTarget;
}

/**
 * Build the GitHub Actions CI workflow YAML.
 */
export function buildCiWorkflow(target: CloudTarget): string {
	const deploy =
		target === "none"
			? `# no-op`
			: `      - name: Deploy to ${target}
        run: ./deploy.sh`;
	return `name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.14
      - run: bun install --frozen-lockfile
      - run: bun test
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${deploy}
`;
}

/**
 * Build a minimal multi-stage Dockerfile.
 */
export function buildDockerfile(): string {
	return `FROM oven/bun:1.3.14 AS builder
WORKDIR /app
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

FROM oven/bun:1.3.14-slim AS runtime
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
EXPOSE 3000
USER bun
CMD ["bun", "run", "start"]
`;
}

/**
 * Build a .env.example template.
 */
export function buildEnvExample(): string {
	return `# Pakalon
PAKALON_BACKEND=https://api.pakalon.dev
PAKALON_API_KEY=

# OpenRouter (master key — server-side)
OPENROUTER_API_KEY=

# Polar (billing)
POLAR_API_KEY=
POLAR_PRODUCT_ID=
POLAR_WEBHOOK_SECRET=

# JWT
PAKALON_JWT_SECRET=
`;
}

/**
 * Build the deploy.sh for the chosen target. Each cloud gets a
 * minimal stub; real deployments extend these with provider SDKs.
 */
export function buildDeployScript(target: CloudTarget): string {
	switch (target) {
		case "aws":
			return `#!/bin/sh
set -e
aws ecs update-service --cluster pakalon --service app --force-new-deployment
`;
		case "digitalocean":
			return `#!/bin/sh
set -e
doctl apps create-deployment ${"$"}APP_ID
`;
		case "azure":
			return `#!/bin/sh
set -e
az webapp deploy --name ${"$"}APP_NAME --resource-group ${"$"}RG --src-path ./dist
`;
		case "gcp":
			return `#!/bin/sh
set -e
gcloud run deploy app --source . --region us-central1 --allow-unauthenticated
`;
		case "none":
			return `#!/bin/sh
echo "no cloud target — local-only deployment"
`;
	}
}

/**
 * Build a minimal Terraform module for the chosen target. Each
 * cloud gets a single-file `main.tf` skeleton that the user can
 * `terraform init && terraform apply` after filling in variables.
 * Per code.md §13.5 / §30: shipping an IaC skeleton is required
 * for the multi-cloud deployer.
 */
export function buildTerraform(target: CloudTarget): string {
	const common = `# Generated by Pakalon Phase 5 — review before applying.
terraform {
  required_version = ">= 1.5"
}
variable "app_name" {
  type    = string
  default = "pakalon-app"
}
variable "image" {
  type    = string
  default = "ghcr.io/OWNER/REPO:latest"
}
variable "port" {
  type    = number
  default = 3000
}
`;
	switch (target) {
		case "aws":
			return `${common}
provider "aws" {
  region = "us-east-1"
}
resource "aws_ecs_service" "app" {
  name            = var.app_name
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.app.arn
  desired_count   = 2
  launch_type     = "FARGATE"
  network_configuration {
    subnets         = data.aws_subnets.default.ids
    security_groups = [aws_security_group.app.id]
    assign_public_ip = true
  }
}
resource "aws_ecs_cluster" "main" { name = var.app_name }
resource "aws_ecs_task_definition" "app" {
  family                   = var.app_name
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = 512
  memory                   = 1024
  container_definitions = jsonencode([{
    name      = var.app_name
    image     = var.image
    essential = true
    portMappings = [{ containerPort = var.port }]
    environment = [
      { name = "PAKALON_RUNTIME", value = "cloud" },
    ]
  }])
}
resource "aws_security_group" "app" {
  name   = var.app_name
  vpc_id = data.aws_vpc.default.id
  ingress {
    from_port   = var.port
    to_port     = var.port
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
data "aws_vpc" "default" { default = true }
data "aws_subnets" "default" { filter { name = "default-for-az" values = ["true"] } }
`;
		case "digitalocean":
			return `${common}
provider "digitalocean" {
  token = var.do_token
}
variable "do_token" { type = string sensitive = true }
resource "digitalocean_app" "main" {
  spec {
    name   = var.app_name
    region = "nyc"
    service {
      name               = var.app_name
      http_port          = var.port
      instance_count     = 2
      instance_size_slug = "professional-xs"
      image { registry_type = "DOCKER_HUB" repository = "pakalon/app" tag = "latest" }
      env { key = "PAKALON_RUNTIME" value = "cloud" scope = "RUN_TIME" }
    }
  }
}
`;
		case "azure":
			return `${common}
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "main" {
  name     = var.app_name
  location = "East US"
}
resource "azurerm_service_plan" "main" {
  name                = var.app_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  os_type             = "Linux"
  sku_name             = "P1v3"
}
resource "azurerm_linux_web_app" "main" {
  name                = var.app_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  service_plan_id     = azurerm_service_plan.main.id
  site_config {
    application_stack {
      docker_image     = var.image
      docker_image_tag = "latest"
    }
  }
  app_settings = {
    PAKALON_RUNTIME = "cloud"
  }
}
`;
		case "gcp":
			return `${common}
provider "google" {
  project = var.project
  region  = "us-central1"
}
variable "project" { type = string }
resource "google_cloud_run_service" "main" {
  name     = var.app_name
  location = "us-central1"
  template {
    spec {
      containers {
        image = var.image
        ports { container_port = var.port }
        env { name = "PAKALON_RUNTIME" value = "cloud" }
      }
    }
  }
  traffic {
    percent         = 100
    latest_revision = true
  }
}
`;
		case "none":
			return "# No cloud target — local-only deployment.\n";
	}
}

export function emitPhase5Files(ctx: Phase5Context): string[] {
	const written: string[] = [];
	fs.mkdirSync(ctx.phase5Dir, { recursive: true });
	fs.mkdirSync(path.join(ctx.projectDir, ".github", "workflows"), { recursive: true });

	fs.writeFileSync(
		path.join(ctx.projectDir, ".github", "workflows", "ci.yml"),
		buildCiWorkflow(ctx.cloudTarget),
		"utf-8",
	);
	written.push(".github/workflows/ci.yml");

	// Add a second workflow for issue auto-labelling per CLI-req.md
	// and code.md §13.5 ("gh issue automation hook"). When issues
	// are opened, a label is auto-applied based on the issue body
	// keywords. This is the simplest, dependency-free variant.
	fs.writeFileSync(
		path.join(ctx.projectDir, ".github", "workflows", "issue-triage.yml"),
		buildIssueTriageWorkflow(),
		"utf-8",
	);
	written.push(".github/workflows/issue-triage.yml");

	fs.writeFileSync(path.join(ctx.projectDir, "Dockerfile"), buildDockerfile(), "utf-8");
	written.push("Dockerfile");

	fs.writeFileSync(path.join(ctx.projectDir, ".env.example"), buildEnvExample(), "utf-8");
	written.push(".env.example");

	fs.writeFileSync(path.join(ctx.projectDir, "deploy.sh"), buildDeployScript(ctx.cloudTarget), "utf-8");
	fs.chmodSync(path.join(ctx.projectDir, "deploy.sh"), 0o755);
	written.push("deploy.sh");

	// IaC skeleton for the chosen cloud. Always written, even for
	// `none` (the no-op template is a no-op so the user can diff).
	fs.mkdirSync(path.join(ctx.projectDir, "infra", ctx.cloudTarget), { recursive: true });
	fs.writeFileSync(
		path.join(ctx.projectDir, "infra", ctx.cloudTarget, "main.tf"),
		buildTerraform(ctx.cloudTarget),
		"utf-8",
	);
	written.push(`infra/${ctx.cloudTarget}/main.tf`);

	const summary = [
		`# Phase 5: Deployment Summary`,
		``,
		`Cloud target: ${ctx.cloudTarget}`,
		ctx.repoFullName ? `GitHub: ${ctx.repoFullName}` : "GitHub: not yet linked",
		``,
		`## Files generated`,
		``,
		...written.map(f => `- ${f}`),
		``,
		`## Next steps`,
		``,
		`1. git init && git add -A && git commit -m "feat: phase 5 deploy"`,
		`2. gh repo create ${ctx.repoFullName ?? "your-name/repo"} --public --source=.`,
		`3. git push -u origin main`,
		`4. configure cloud credentials (see .env.example)`,
		`5. ./deploy.sh`,
	].join("\n");
	fs.writeFileSync(path.join(ctx.phase5Dir, "phase-5.md"), summary, "utf-8");
	written.push("phase-5.md");

	logger.info("Phase 5 emitted", { count: written.length });
	return written;
}

/**
 * Build the issue-triage GitHub Actions workflow. Per code.md §13.5,
 * this provides the `gh issue` automation hook: a new issue gets
 * auto-labelled `bug` / `enhancement` / `question` based on the
 * issue body keywords. The workflow uses the official
 * `actions/labeler` action with a small inline config.
 */
function buildIssueTriageWorkflow(): string {
	return `name: issue-triage
on:
  issues:
    types: [opened]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Apply labels based on issue body
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.issue.body || '').toLowerCase();
            const labels = new Set();
            if (/\\b(crash|error|bug|broken|stack\\s?trace|fail)/.test(body)) labels.add('bug');
            if (/\\b(feature|enhancement|request|suggestion|would be nice)/.test(body)) labels.add('enhancement');
            if (/\\b(how|why|what|when|where|question|help)/.test(body)) labels.add('question');
            if (labels.size > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: Array.from(labels),
              });
            }
`;
}

function path(...parts: string[]): string {
	return parts.join("/");
}
