/**
 * Vercel agent-skills clone for Pakalon Phase 1.
 *
 * The requirements list three reference repos for design skills:
 *   1. https://github.com/vercel-labs/agent-skills
 *   2. https://skills.sh/vercel-labs/agent-skills
 *   3. https://github.com/nextlevelbuilder/ui-ux-pro-max-skill
 *   4. https://agentskills.io (mirror via agentskills-io/agentskills.io)
 *
 * Phase 1's design.md is generated by picking the relevant skills
 * from these. This module lazily clones them on first use and
 * indexes the resulting `SKILL.md` files so the LLM can search
 * them via `pickSkills(query)`.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { logger } from "@oh-my-pi/pi-utils";
import { $ } from "bun";

const REPOS = [
	{ url: "https://github.com/vercel-labs/agent-skills.git", name: "vercel/agent-skills" },
	{ url: "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill.git", name: "nextlevelbuilder/ui-ux-pro-max-skill" },
	{ url: "https://github.com/agentskills-io/agentskills.io.git", name: "agentskills-io/agentskills.io" },
] as const;

const CACHE_DIR = path.join(process.env.HOME ?? "/tmp", ".pakalon", "agent-skills");

export interface SkillMatch {
	repo: string;
	path: string;
	content: string;
	score: number;
}

let clonePromise: Promise<void> | null = null;

/**
 * Ensure the agent-skills repos are cloned into the cache dir.
 * Subsequent calls are a no-op. Uses shallow clones to keep the
 * footprint small.
 */
export function ensureCloned(force: boolean = false): Promise<void> {
	if (!force && clonePromise) return clonePromise;
	clonePromise = (async () => {
		fs.mkdirSync(CACHE_DIR, { recursive: true });
		for (const r of REPOS) {
			const target = path.join(CACHE_DIR, r.name);
			if (!force && fs.existsSync(path.join(target, "SKILL.md"))) continue;
			logger.info("agent-skills: cloning", { repo: r.url, target });
			if (fs.existsSync(target)) {
				await $`git -C ${target} pull --depth 1 --ff-only`.quiet().nothrow();
			} else {
				await $`git clone --depth 1 ${r.url} ${target}`.quiet().nothrow();
			}
		}
	})();
	return clonePromise;
}

/**
 * Read all SKILL.md files from the cache, tokenize, and rank
 * by Jaccard similarity against the query.
 */
export async function pickSkills(query: string, topK: number = 5): Promise<SkillMatch[]> {
	await ensureCloned();
	const qTokens = tokenize(query);
	const matches: SkillMatch[] = [];
	for (const r of REPOS) {
		const dir = path.join(CACHE_DIR, r.name);
		if (!fs.existsSync(dir)) continue;
		const files = findSkillFiles(dir);
		for (const file of files) {
			try {
				const content = fs.readFileSync(file, "utf-8");
				const fTokens = tokenize(content);
				const score = jaccard(qTokens, fTokens);
				if (score > 0) {
					matches.push({ repo: r.name, path: file, content: content.slice(0, 8_000), score });
				}
			} catch {
				/* ignore */
			}
		}
	}
	matches.sort((a, b) => b.score - a.score);
	return matches.slice(0, topK);
}

function findSkillFiles(dir: string): string[] {
	const out: string[] = [];
	function walk(d: string, depth: number) {
		if (depth > 4) return;
		try {
			for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
				if (entry.name === ".git" || entry.name === "node_modules") continue;
				const p = path.join(d, entry.name);
				if (entry.isDirectory()) walk(p, depth + 1);
				else if (entry.isFile() && /SKILL\.md$/i.test(entry.name)) out.push(p);
			}
		} catch {
			/* ignore */
		}
	}
	walk(dir, 0);
	return out;
}

function tokenize(s: string): Set<string> {
	return new Set(
		s
			.toLowerCase()
			.replace(/[^a-z0-9\s-]+/g, " ")
			.split(/\s+/)
			.filter(w => w.length >= 3),
	);
}

function jaccard(a: Set<string>, b: Set<string>): number {
	if (a.size === 0 || b.size === 0) return 0;
	let inter = 0;
	for (const t of a) if (b.has(t)) inter++;
	return inter / (a.size + b.size - inter);
}
