"""DeviceCode ORM model."""
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class DeviceCode(Base):
    """A 6-digit device authentication code issued to a CLI machine."""

    __tablename__ = "device_codes"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    # Stable per-machine identifier generated by CLI
    device_id: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    # 6-digit numeric code displayed to the user
    code: Mapped[str] = mapped_column(String(6), nullable=False)
    # Supabase user id — set after the user confirms on the website
    supabase_user_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # Pakalon DB user id — set after confirmation
    user_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    # pending | approved | expired
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    machine_id: Mapped[str | None] = mapped_column(String(512), nullable=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(tz=timezone.utc),
    )

    def __repr__(self) -> str:
        return f"<DeviceCode device_id={self.device_id!r} status={self.status!r}>"
