/**
 * Regressions for two issues that together produced silent edit failures on
 * auto-generated files:
 *
 *   1. The streaming auto-generated guard was gated behind `edit.streamingAbort`
 *      (default false), so it never fired in default configs.
 *   2. `executeSinglePathEntries` (multi-edit, single-path orchestrator)
 *      swallowed per-entry exceptions and returned an aggregate result with
 *      no `isError` flag. The UI then fell through to the streaming preview
 *      branch and rendered the *proposed* diff, making a hard failure look
 *      indistinguishable from success.
 */

import { afterEach, beforeEach, expect, it, vi } from "bun:test";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { Agent, type AgentTool } from "@oh-my-pi/pi-agent-core";
import { type AssistantMessage, getBundledModel, type StopReason, type ToolCall } from "@oh-my-pi/pi-ai";
import { createMockModel } from "@oh-my-pi/pi-ai/providers/mock";
import { AssistantMessageEventStream } from "@oh-my-pi/pi-ai/utils/event-stream";
import { ModelRegistry } from "@oh-my-pi/pi-coding-agent/config/model-registry";
import { resetSettingsForTest, Settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import { EditTool } from "@oh-my-pi/pi-coding-agent/edit";
import { AgentSession } from "@oh-my-pi/pi-coding-agent/session/agent-session";
import { AuthStorage } from "@oh-my-pi/pi-coding-agent/session/auth-storage";
import { SessionManager } from "@oh-my-pi/pi-coding-agent/session/session-manager";
import type { ToolSession } from "@oh-my-pi/pi-coding-agent/tools";
import * as autoGeneratedGuard from "@oh-my-pi/pi-coding-agent/tools/auto-generated-guard";
import { ToolError } from "@oh-my-pi/pi-coding-agent/tools/tool-errors";
import { Snowflake } from "@oh-my-pi/pi-utils";
import * as z from "zod/v4";

function createAssistantMessage(content: AssistantMessage["content"], stopReason: StopReason): AssistantMessage {
	return {
		role: "assistant",
		content,
		api: "anthropic-messages",
		provider: "anthropic",
		model: "mock",
		usage: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
			totalTokens: 0,
			cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
		},
		stopReason,
		timestamp: Date.now(),
	};
}

function createToolCall(id: string, args: Record<string, unknown>): ToolCall {
	return { type: "toolCall", id, name: "edit", arguments: args };
}

function lastAssistantMessage(messages: Array<{ role: string }>): AssistantMessage | undefined {
	for (let i = messages.length - 1; i >= 0; i--) {
		const msg = messages[i];
		if (msg.role === "assistant") return msg as AssistantMessage;
	}
	return undefined;
}

function buildMockEditTool(): AgentTool {
	const schema = z.object({
		path: z.string(),
		diff: z.string(),
		op: z.string().optional(),
		rename: z.string().optional(),
	});
	return {
		name: "edit",
		label: "Edit",
		description: "",
		parameters: schema,
		async execute() {
			return { content: [{ type: "text", text: "ok" }] };
		},
	};
}

function createSessionWith(
	tempDir: string,
	streamFn: Agent["streamFn"],
	tool: AgentTool,
	settingsOverrides: Record<string, unknown> = {},
): Promise<{ agent: Agent; session: AgentSession; authStorage: AuthStorage }> {
	return (async () => {
		const model = getBundledModel("anthropic", "claude-sonnet-4-5")!;
		const agent = new Agent({
			getApiKey: () => "test-key",
			initialState: { model, systemPrompt: ["Test"], tools: [tool] },
			streamFn,
		});
		const sessionManager = SessionManager.inMemory(tempDir);
		const settings = Settings.isolated(settingsOverrides);
		const authStorage = await AuthStorage.create(path.join(tempDir, "testauth.db"));
		authStorage.setRuntimeApiKey("anthropic", "test-key");
		const modelRegistry = new ModelRegistry(authStorage, path.join(tempDir, "models.yml"));
		return {
			agent,
			session: new AgentSession({ agent, sessionManager, settings, modelRegistry }),
			authStorage,
		};
	})();
}

function streamForSingleToolCall(
	filePath: string,
	diff: string,
	abortSignalRef: { current?: AbortSignal },
): Agent["streamFn"] {
	let callIndex = 0;
	return (_model, _context, options) => {
		abortSignalRef.current = options?.signal;
		const stream = new AssistantMessageEventStream();
		const toolCallId = "call_edit_regression";
		let aborted = false;

		const notifyAbort = () => {
			if (aborted) return;
			aborted = true;
			const partial = createToolCall(toolCallId, { path: filePath, diff });
			stream.push({
				type: "toolcall_delta",
				contentIndex: 0,
				delta: "",
				partial: createAssistantMessage([partial], "stop"),
			});
			stream.push({ type: "error", reason: "aborted", error: createAssistantMessage([], "aborted") });
		};
		options?.signal?.addEventListener("abort", notifyAbort, { once: true });

		queueMicrotask(async () => {
			if (callIndex > 0) {
				const finalMessage = createAssistantMessage([{ type: "text", text: "done" }], "stop");
				stream.push({ type: "done", reason: "stop", message: finalMessage });
				callIndex++;
				return;
			}
			stream.push({ type: "start", partial: createAssistantMessage([], "stop") });

			const startCall = createToolCall(toolCallId, { path: filePath, diff: "" });
			stream.push({
				type: "toolcall_start",
				contentIndex: 0,
				partial: createAssistantMessage([startCall], "stop"),
			});

			// Emit the full diff in one delta to simplify timing; the abort path
			// should still preempt before the call completes (or, if it loses the
			// race, the next per-entry `assertEditableFile` is the hard stop).
			let acc = "";
			for (const chunk of diff.match(/.{1,4}/g) ?? []) {
				if (aborted) return;
				acc += chunk;
				const partial = createToolCall(toolCallId, { path: filePath, diff: acc });
				stream.push({
					type: "toolcall_delta",
					contentIndex: 0,
					delta: chunk,
					partial: createAssistantMessage([partial], "stop"),
				});
				await Bun.sleep(0);
			}
			if (aborted) return;

			const finalCall = createToolCall(toolCallId, { path: filePath, diff });
			const finalMessage = createAssistantMessage([finalCall], "toolUse");
			stream.push({ type: "toolcall_end", contentIndex: 0, toolCall: finalCall, partial: finalMessage });
			stream.push({ type: "done", reason: "toolUse", message: finalMessage });
			callIndex++;
		});

		return stream;
	};
}

let tempDir: string;

beforeEach(() => {
	tempDir = path.join(os.tmpdir(), `pi-edit-regressions-${Snowflake.next()}`);
	fs.mkdirSync(tempDir, { recursive: true });
});

afterEach(async () => {
	if (tempDir) fs.rmSync(tempDir, { recursive: true, force: true });
});

it("auto-generated streaming abort fires even when edit.streamingAbort is disabled", async () => {
	// The setting `edit.streamingAbort` defaults to false. The auto-generated
	// guard must NOT be gated by that flag — editing a generated file is never
	// the user's intent regardless of the patch-preview verification setting.
	const checkSpy = vi
		.spyOn(autoGeneratedGuard, "assertEditableFile")
		.mockRejectedValue(new ToolError("Cannot modify auto-generated file"));

	await Bun.write(path.join(tempDir, "generated.ts"), "// AUTO-GENERATED\nexport const x = 1;\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = streamForSingleToolCall(
		"generated.ts",
		"@@\n-export const x = 1;\n+export const x = 2;\n",
		abortSignalRef,
	);

	// Explicitly disable edit.streamingAbort to confirm the auto-generated path
	// is independent of it.
	const { agent, session, authStorage } = await createSessionWith(tempDir, streamFn, buildMockEditTool(), {
		"edit.streamingAbort": false,
	});
	const abortSpy = vi.spyOn(agent, "abort");

	try {
		await session.prompt("apply patch");

		expect(checkSpy).toHaveBeenCalled();
		expect(abortSpy).toHaveBeenCalled();
		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant?.stopReason).toBe("aborted");
	} finally {
		checkSpy.mockRestore();
		abortSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("multi-entry edit on an auto-generated file surfaces isError + error text instead of silently faking success", async () => {
	// Direct invocation of the patch-mode EditTool with two entries against an
	// auto-generated file. The orchestrator (executeSinglePathEntries) must NOT
	// swallow the per-entry errors — it must mark the aggregate result with
	// isError: true so the renderer takes the error branch instead of falling
	// through to the streaming preview (which displays the *proposed* diff and
	// looks identical to success).
	const generatedPath = path.join(tempDir, "generated.ts");
	await Bun.write(
		generatedPath,
		"// Code generated by sqlc. DO NOT EDIT.\nexport const foo = 1;\nexport const bar = 2;\n",
	);

	const originalVariant = Bun.env.PI_EDIT_VARIANT;
	Bun.env.PI_EDIT_VARIANT = "patch";

	// The auto-generated guard reads from the *global* settings singleton, so we
	// must initialize it (the per-tool `Settings.isolated(...)` we pass into the
	// EditTool isn't what the guard sees).
	resetSettingsForTest();
	await Settings.init({ inMemory: true, cwd: tempDir, overrides: { "edit.blockAutoGenerated": true } });

	try {
		const sessionFile = path.join(tempDir, "session.jsonl");
		const sessionDir = path.join(tempDir, "session");
		const session = {
			cwd: tempDir,
			hasUI: false,
			getSessionFile: () => sessionFile,
			getSessionSpawns: () => "*",
			getArtifactsDir: () => sessionDir,
			allocateOutputArtifact: async (toolType: string) => {
				fs.mkdirSync(sessionDir, { recursive: true });
				return { id: "a-1", path: path.join(sessionDir, `a-1.${toolType}.log`) };
			},
			settings: Settings.isolated({ "edit.blockAutoGenerated": true }),
			enableLsp: false,
		} as ToolSession;

		const editTool = new EditTool(session);
		const result = await editTool.execute("test-multi-entry", {
			path: generatedPath,
			edits: [
				{ op: "update", diff: "@@\n-export const foo = 1;\n+export const foo = 11;\n" },
				{ op: "update", diff: "@@\n-export const bar = 2;\n+export const bar = 22;\n" },
			],
		});

		// File is untouched on disk.
		const contentOnDisk = await Bun.file(generatedPath).text();
		expect(contentOnDisk).toContain("export const foo = 1;");
		expect(contentOnDisk).toContain("export const bar = 2;");

		// Aggregate result must signal an error so the renderer doesn't draw
		// the streaming preview as if it succeeded.
		expect(result.isError).toBe(true);

		// Both per-entry failures must be preserved in the content text so the
		// agent (and the error renderer) see the real cause.
		const text = (result.content?.find(c => c.type === "text") as { text?: string } | undefined)?.text ?? "";
		const occurrences = text.match(/Cannot modify auto-generated file/g) ?? [];
		expect(occurrences.length).toBe(2);

		// `details.diff` must not contain a fabricated diff that would mislead the
		// renderer's preview-fallback branch into showing the proposed change.
		const details = result.details as { diff?: string } | undefined;
		expect(details?.diff ?? "").toBe("");
	} finally {
		if (originalVariant === undefined) {
			delete Bun.env.PI_EDIT_VARIANT;
		} else {
			Bun.env.PI_EDIT_VARIANT = originalVariant;
		}
	}
});

it("agent-loop propagates explicit isError from a tool result to the wire", async () => {
	// Validates the boundary fix: `coerceToolResult` preserves a tool-self-reported
	// `isError: true`, and agent-loop honors it (emits tool_execution_end with
	// isError=true and constructs a tool-result message with isError=true).
	const schema = z.object({ note: z.string().optional() });
	const errorTool: AgentTool = {
		name: "edit",
		label: "Edit",
		description: "",
		parameters: schema,
		async execute() {
			return {
				content: [{ type: "text", text: "intentional non-throwing failure" }],
				details: {},
				isError: true,
			};
		},
	};

	const mock = createMockModel({
		responses: [
			{
				content: [{ type: "toolCall", id: "call_self_error", name: "edit", arguments: {} }],
				stopReason: "toolUse",
			},
			{ content: ["done"], stopReason: "stop" },
		],
	});

	const { session, authStorage } = await createSessionWith(tempDir, mock.stream, errorTool);
	try {
		await session.prompt("trigger self-error");

		const toolResult = session.state.messages.find(m => m.role === "toolResult") as
			| { isError?: boolean; content: Array<{ type: string; text?: string }> }
			| undefined;
		expect(toolResult).toBeDefined();
		expect(toolResult?.isError).toBe(true);
		const text = toolResult?.content?.find(c => c.type === "text")?.text ?? "";
		expect(text).toContain("intentional non-throwing failure");
	} finally {
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});
